/**
 * One Piece Universe Characters
 * Character types: pirate, marine, revolutionary, shichibukai, yonko, civilian
 * Difficulty levels: 1 (easiest) to 5 (hardest)
 */

export interface OnePieceCharacterSeed {
  name: string;
  type:
    | 'pirate'
    | 'marine'
    | 'revolutionary'
    | 'shichibukai'
    | 'yonko'
    | 'civilian';
  difficulty: number;
  hints: string[];
}

// Example characters demonstrating the structure
// Add more characters following this pattern
export const onePieceCharacters: OnePieceCharacterSeed[] = [
  // ==================== ÉQUIPAGE DU CHAPEAU DE PAILLE ====================
  {
    name: 'Monkey D. Luffy (Chapeau de Paille)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Son grand-père est un héros légendaire de la Marine qui l'a élevé à la dure.",
      'Il a deux frères adoptifs avec qui il a fait un serment de fraternité enfant.',
      'Un pirate lui a sauvé la vie en sacrifiant son bras contre un monstre marin.',
      'Il a déclaré la guerre au Gouvernement Mondial pour sauver une seule amie.',
      "Son fruit lui donnait un corps élastique, mais sa vraie nature s'est révélée être mythique.",
      'Il a vaincu trois des Quatre Empereurs au cours de son voyage.',
      'Sa prime actuelle est de 3 milliards de Berrys.',
      'Capitaine au chapeau de paille, son rêve est de devenir le Roi des Pirates.',
    ],
  },
  {
    name: 'Roronoa Zoro (Chasseur de Pirates)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "La mort de sa rivale d'enfance l'a poussé à poursuivre leur rêve commun.",
      "Il s'est laissé capturer pour sauver une petite fille d'un noble corrompu.",
      'Il a accepté toute la douleur de son capitaine pour le sauver face à un tyran.',
      "Il s'est entraîné pendant deux ans sous la tutelle de son plus grand rival.",
      'Il possède une épée maudite et une autre qui absorbe le Haki de son utilisateur.',
      "Son sens de l'orientation est catastrophique - il se perd même en ligne droite.",
      'Il pratique un style de combat unique utilisant trois sabres simultanément.',
      'Épéiste aux cheveux verts, son rêve est de devenir le meilleur au monde.',
    ],
  },
  {
    name: 'Nami (Chatte Voleuse)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Orpheline recueillie par une femme soldat après une bataille sanglante.',
      'Elle a passé huit ans à voler pour racheter la liberté de son village.',
      "Le chef qui l'exploitait a été trahi par un Marine corrompu annulant leur accord.",
      "Elle a d'abord trahi celui qui deviendrait son capitaine avant de le rejoindre.",
      'Son arme crée des phénomènes météorologiques grâce à des technologies avancées.',
      "Elle est obsédée par l'argent et gère les finances de son groupe.",
      'Experte en cartographie, elle rêve de dessiner la carte du monde entier.',
      "Navigatrice aux cheveux orange avec un tatouage de mandarine sur l'épaule.",
    ],
  },
  {
    name: 'Usopp (Sogeking / God Usopp)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Enfant, il criait chaque jour un mensonge qui s'est réalisé des années plus tard.",
      "Son père l'a abandonné pour suivre son rêve, rejoignant un Empereur.",
      'Il a quitté temporairement ses amis après un désaccord sur leur navire.',
      'Son alter-ego masqué est apparu quand il devait sauver une amie condamnée.',
      'À Dressrosa, il a éveillé une capacité rare en sauvant des milliers de personnes.',
      'Ses mensonges ont tendance à devenir réalité de façon troublante.',
      "Son père est le tireur d'élite d'un Empereur aux cheveux roux.",
      'Tireur au long nez, il rêve de devenir un brave guerrier des mers.',
    ],
  },
  {
    name: 'Sanji (Jambe Noire)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Il a failli mourir de faim sur un rocher avec celui qui deviendrait son mentor.',
      "Son code d'honneur lui interdit absolument de frapper une femme.",
      "Il est né dans une famille royale qui l'a rejeté car il avait des émotions.",
      'Ses frères et sœurs sont des soldats génétiquement modifiés sans sentiments.',
      'Il a détruit un costume technologique pour couper les liens avec son passé.',
      "Ses jambes peuvent s'enflammer grâce à une technique qu'il a développée seul.",
      'Cuisinier aux sourcils en spirale, il rêve de trouver All Blue.',
      'Il travaillait dans un restaurant flottant en East Blue avant de partir en mer.',
    ],
  },
  {
    name: 'Tony Tony Chopper (Le Renne au Nez Bleu)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Rejeté par son troupeau à cause de sa différence, il a erré seul dans la neige.',
      "Un médecin excentrique au drapeau pirate l'a recueilli et nommé.",
      'Ce mentor est mort en tentant de guérir un roi avec un champignon mortel.',
      'Il a étudié six ans sous une docteure centenaire après cette tragédie.',
      'La Marine le prend pour une mascotte, lui donnant une prime ridicule.',
      "Il peut prendre plusieurs formes de combat grâce à une drogue qu'il a inventée.",
      'Son fruit lui permet de parler et de prendre forme humaine.',
      "Médecin au nez bleu, c'est un renne qui rêve de guérir toutes les maladies.",
    ],
  },
  {
    name: "Nico Robin (L'Enfant Démon)",
    type: 'pirate',
    difficulty: 1,
    hints: [
      'À 8 ans, elle a vu sa maison natale détruite par une attaque militaire massive.',
      'Elle est la seule survivante capable de déchiffrer une écriture interdite.',
      'Pendant 20 ans, elle a fui en travaillant pour des criminels par nécessité.',
      'Elle a déclaré vouloir vivre après que des pirates aient brûlé un drapeau pour elle.',
      'Elle a étudié deux ans avec une armée qui combat le Gouvernement.',
      "Son fruit lui permet de faire éclore des parties de son corps n'importe où.",
      "Elle cherche la vérité sur un siècle effacé de l'histoire.",
      'Archéologue qui peut lire les Ponéglyphes, la seule au monde.',
    ],
  },
  {
    name: 'Franky (Cutty Flam / Le Cyborg)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Abandonné par des pirates à 10 ans, il a été recueilli par un constructeur naval légendaire.',
      'Son mentor a été condamné à mort à cause de navires que lui-même avait construits.',
      "Percuté par un train, il s'est reconstruit avec des pièces de fortune.",
      'Il a dirigé un groupe de démonteurs de navires pendant des années.',
      'Il a construit le navire de ses compagnons actuels avec le bois le plus rare au monde.',
      'Ses armes secrètes fonctionnent au cola comme carburant.',
      'Son vrai nom a été abandonné après la mort de son mentor.',
      'Charpentier cyborg en slip de bain, il a construit le Thousand Sunny.',
    ],
  },
  {
    name: 'Brook (Soul King)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Ancien membre d'une garde royale, il est devenu pirate par passion musicale.",
      'Son équipage entier est mort empoisonné il y a plus de 50 ans.',
      'Il a erré seul sur un navire fantôme pendant cinq décennies.',
      'Sa capacité lui a permis de revenir à la vie, mais son corps était déjà squelettique.',
      'Il a été une star mondiale de la musique pendant deux ans sous un autre nom.',
      'Son épée peut geler les adversaires grâce au pouvoir de son âme.',
      'Son crâne porte une fissure du combat où il est mort la première fois.',
      'Musicien squelettique, il fait des blagues sur les os et veut revoir une baleine.',
    ],
  },
  {
    name: 'Jinbe (Le Chevalier de la Mer)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Il a grandi dans un quartier pauvre où son peuple était discriminé.',
      "Il a rejoint un équipage fondé pour protéger les siens de l'esclavage.",
      'Il a accepté un titre gouvernemental pour protéger son île natale.',
      'Il a renoncé à ce titre en refusant de combattre dans une guerre.',
      "Il a aidé un futur Empereur à s'évader de la prison la plus sécurisée du monde.",
      'Il a servi temporairement sous une Empereur avant de la défier publiquement.',
      "Sa maîtrise d'un art martial lui permet de contrôler l'eau comme une arme.",
      "Timonier de type requin-baleine, dernier membre officiel à avoir rejoint l'équipage.",
    ],
  },

  // ==================== EMPEREURS ET LEURS ÉQUIPAGES ====================
  {
    name: 'Shanks le Roux',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Il était mousse sur le navire du seul homme à avoir trouvé le One Piece.',
      "Il a perdu son bras gauche en sauvant un enfant d'un monstre marin.",
      "Ses trois cicatrices à l'œil lui ont été infligées avant le début de l'histoire principale.",
      "Il a mis fin à la plus grande guerre de l'ère actuelle en s'interposant seul.",
      "Son Haki a endommagé un navire rien qu'en marchant dessus.",
      'Il peut rencontrer les dirigeants du monde malgré son statut de criminel.',
      'Il a confié un chapeau de paille à un enfant en lui faisant faire une promesse.',
      'Empereur aux cheveux roux, capitaine du Red Force.',
    ],
  },
  {
    name: 'Marshall D. Teach (Barbe Noire)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Il s'est caché dans l'ombre pendant des décennies, attendant son heure.",
      "Il a tué un camarade pour voler quelque chose qu'il convoitait depuis toujours.",
      'Il a livré le fils de Roger à la Marine pour obtenir un titre officiel.',
      'Il est le seul être connu à posséder deux pouvoirs normalement incompatibles.',
      'Il a volé une capacité légendaire directement sur un cadavre à Marine Ford.',
      "Il a libéré les pires criminels d'une prison pour renforcer ses forces.",
      'Son fruit des ténèbres peut annuler les pouvoirs des autres.',
      'Empereur qui possède les pouvoirs des ténèbres et des tremblements.',
    ],
  },
  {
    name: 'Edward Newgate (Barbe Blanche)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Orphelin, il n'a jamais voulu de trésor - seulement une famille.",
      "Il faisait partie d'un équipage légendaire avant de fonder le sien.",
      'Il considérait tous ses subordonnés comme ses enfants, les protégeant férocement.',
      "Il a mené la plus grande guerre maritime de l'histoire pour sauver un de ses fils.",
      'Malgré sa maladie, il est mort debout, sans aucune blessure dans le dos.',
      "Son corps portait 267 blessures d'épée, 152 balles et 46 boulets de canon.",
      'Son fruit pouvait créer des tremblements de terre et des tsunamis.',
      "Surnommé l'Homme le Plus Fort, il était l'égal du Roi des Pirates.",
    ],
  },
  {
    name: 'Kaido (Kaido aux Cent Bêtes)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Il a été capturé 18 fois et condamné à mort 40 fois sans jamais mourir.',
      'Son hobby est de tenter de se suicider, mais rien ne fonctionne sur lui.',
      "Il faisait partie d'un équipage légendaire dans sa jeunesse.",
      "Il a pris le contrôle d'un pays isolé il y a 20 ans par la trahison.",
      'Il voulait créer une armée de soldats aux pouvoirs artificiels.',
      'Son fruit mythique lui permet de se transformer en dragon oriental.',
      'Il a été vaincu après plusieurs affrontements par une alliance de pirates.',
      'Surnommé la Créature la Plus Puissante, il régnait depuis Onigashima.',
    ],
  },
  {
    name: 'Charlotte Linlin (Big Mom)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Abandonnée par ses parents à 5 ans à cause de sa taille et sa force.',
      "Lors d'une crise, elle a fait disparaître tous ceux qui s'occupaient d'elle.",
      "Elle a 85 enfants qu'elle utilise pour des alliances politiques.",
      "Elle entre dans des rages meurtrières quand elle n'obtient pas ce qu'elle veut manger.",
      "Son territoire est composé d'objets et d'aliments rendus vivants.",
      'Son fruit lui permet de manipuler les âmes et de créer des serviteurs.',
      'Sa prime dépassait 4 milliards avant sa défaite à Wano.',
      "Empereur aux pouvoirs d'âme, vaincue par Law et Kid.",
    ],
  },
  {
    name: 'Portgas D. Ace (Poing Ardent)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Sa mère l'a porté 20 mois pour cacher son existence au monde entier.",
      'Il a grandi avec deux frères adoptifs, élevé par des bandits des montagnes.',
      'Il a refusé une offre officielle du Gouvernement par loyauté envers son père adoptif.',
      "Il a poursuivi un traître pour venger l'honneur de sa famille.",
      "Sa capture a déclenché la plus grande guerre de l'ère moderne.",
      "Il est mort en protégeant son petit frère d'une attaque de magma.",
      'Son fruit de feu a été récupéré par son autre frère des années plus tard.',
      'Fils biologique du Roi des Pirates, commandant de la 2ème division de Barbe Blanche.',
    ],
  },
  {
    name: 'Marco le Phénix',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Il était présent lors de la rencontre historique entre deux légendes rivales.',
      'Après la mort de son capitaine, il a mené une guerre de vengeance et a perdu.',
      'Il est devenu médecin sur une île pour protéger ceux qui y vivaient.',
      'Il a rejoint une alliance contre un Empereur pour honorer une vieille dette.',
      'Son fruit mythique lui confère des flammes bleues qui guérissent.',
      "Sa transformation lui donne l'apparence d'un oiseau légendaire.",
      "Il était le commandant de la 1ère division d'un Empereur défunt.",
      'Ses flammes régénératrices le rendent presque impossible à tuer.',
    ],
  },
  {
    name: 'Charlotte Katakuri',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Il n'avait jamais touché le sol du dos en combat avant un certain duel.",
      'Enfant, il cachait un trait physique qui lui valait des moqueries.',
      'Quand sa sœur a été attaquée à cause de lui, il a juré de ne plus jamais perdre.',
      'Il mange seul, allongé, pour que personne ne voie son visage.',
      "Son Haki de l'Observation lui permet de voir quelques secondes dans le futur.",
      "Il s'est infligé une blessure pour compenser une interférence extérieure.",
      'Son fruit lui permet de créer et contrôler une substance gluante et comestible.',
      'Plus puissant des Sweet Commanders, sa prime dépassait le milliard.',
    ],
  },
  {
    name: 'King (Alber le Lunaria)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      "Il est le dernier survivant d'un peuple autrefois appelé les dieux.",
      'Enfant, il était cobaye du Gouvernement Mondial dans des expériences.',
      "Un Empereur l'a libéré et lui a proposé de conquérir le monde ensemble.",
      'Il cache son visage car son peuple est recherché par le pouvoir mondial.',
      'Les siens peuvent produire des flammes et possèdent une résistance surhumaine.',
      'Son fruit ancien lui permet de se transformer en reptile volant préhistorique.',
      'Il a été vaincu quand le secret de sa défense a été percé.',
      "Bras droit d'un Empereur, commandant des All-Stars.",
    ],
  },
  {
    name: 'Queen la Peste',
    type: 'pirate',
    difficulty: 2,
    hints: [
      "Il faisait partie d'un groupe de scientifiques illégaux dans sa jeunesse.",
      'Il a modifié son propre corps avec des armes et un arsenal biologique.',
      'Il est responsable des virus et maladies utilisés par son équipage.',
      'Ses modifications lui permettent de lancer des rayons et des bras extensibles.',
      'Il a un passif avec une famille royale de soldats génétiquement modifiés.',
      'Son fruit ancien lui permet de se transformer en dinosaure au long cou.',
      'Il a été vaincu par un cuisinier qui a éveillé des pouvoirs latents.',
      "L'un des trois All-Stars, il créait des armes biologiques pour son Empereur.",
    ],
  },
  {
    name: 'Ben Beckman',
    type: 'pirate',
    difficulty: 2,
    hints: [
      "Son QI est reconnu comme l'un des plus élevés au monde.",
      'Il est le plus ancien compagnon de son capitaine, présent depuis le début.',
      "Lors d'une grande guerre, il a tenu en respect un Amiral avec son arme.",
      "Sa présence calme contraste avec l'attitude festive de son groupe.",
      'Il utilise un fusil comme arme principale, inhabituel pour son rang.',
      'Il donne souvent des conseils stratégiques à son capitaine.',
      'Il est souvent vu fumant une cigarette dans un calme olympien.',
      "Second d'un Empereur aux cheveux roux, considéré comme extrêmement dangereux.",
    ],
  },
  {
    name: 'Yasopp (Le Tireur)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Il a quitté sa famille pour suivre son rêve malgré sa femme malade.',
      'Sa femme est morte peu après son départ, laissant leur fils orphelin de mère.',
      'Il parle constamment de son enfant avec fierté à ses camarades.',
      "Son Haki lui permet de viser des cibles qu'il ne peut pas voir.",
      "Il évite de confronter son fils par culpabilité de l'avoir abandonné.",
      'Il peut toucher une fourmi à des kilomètres de distance.',
      'Son talent était déjà légendaire dans son village natal.',
      "Tireur d'élite d'un Empereur, père d'un membre des Chapeaux de Paille.",
    ],
  },

  // ==================== GRANDS CORSAIRES ====================
  {
    name: 'Dracule Mihawk (Œil de Faucon)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Il parcourt les mers seul en quête d'adversaires dignes de lui.",
      'Sa rivalité avec un futur Empereur aux cheveux roux est légendaire.',
      "Il a tranché un navire entier d'un seul coup par simple ennui.",
      'Il vit seul dans un château lugubre sur une île sinistre.',
      "Il a accepté d'entraîner celui qui veut le surpasser pendant deux ans.",
      "Après l'abolition d'un système, il a cofondé une organisation de chasseurs.",
      'Ses yeux perçants sont reconnaissables entre mille.',
      'Considéré comme le plus grand épéiste du monde.',
    ],
  },
  {
    name: 'Sir Crocodile (Mr. 0)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Dans sa jeunesse, il rêvait de devenir Roi des Pirates mais a été brisé.',
      'Il a créé une organisation criminelle sous un nom de code numérique.',
      'Son plan était de trouver une arme antique cachée dans un royaume désertique.',
      'Il a été le premier de son rang à être vaincu par le futur Roi des Pirates.',
      'Libéré de prison, il a participé à une grande guerre contre la Marine.',
      'Il a sauvé ses anciens ennemis plusieurs fois pendant cette bataille.',
      "Après l'abolition d'un système, il a cofondé une organisation de chasseurs.",
      'Son fruit lui permet de devenir et contrôler le sable.',
    ],
  },
  {
    name: "Boa Hancock (L'Impératrice Pirate)",
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Elle a été capturée enfant avec ses sœurs par des marchands d'esclaves.",
      'Forcée de manger un fruit pour le divertissement de ses maîtres nobles.',
      "Un aventurier légendaire l'a libérée lors d'un assaut héroïque.",
      'Elle dirige un royaume exclusivement féminin depuis sa libération.',
      "Elle est tombée amoureuse du seul homme à l'avoir vue sans jugement.",
      'Sa beauté peut littéralement pétrifier ceux qui la désirent.',
      "Elle a aidé celui qu'elle aime à infiltrer une prison et une guerre.",
      "Considérée comme la plus belle femme du monde, impératrice d'Amazon Lily.",
    ],
  },
  {
    name: 'Bartholomew Kuma (Le Tyran)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      "Ancien roi d'un petit royaume, il a été persécuté par le pouvoir mondial.",
      "Il a rejoint une armée rebelle et est devenu l'un de ses commandants.",
      'Pour protéger sa fille, il a accepté de devenir un cobaye scientifique.',
      'Son fruit peut repousser tout, y compris des concepts abstraits comme la douleur.',
      'Il a sauvé un équipage entier en les envoyant aux quatre coins du monde.',
      'Sa transformation progressive a effacé sa personnalité et ses souvenirs.',
      'Il est devenu une arme humaine au service du Gouvernement.',
      'Ancien révolutionnaire transformé en cyborg sans volonté.',
    ],
  },
  {
    name: 'Trafalgar D. Water Law (Le Chirurgien de la Mort)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Seul survivant d'un génocide, il a vu sa ville entière exterminée.",
      'Enfant, il a infiltré un équipage criminel pour se venger du monde.',
      "Le frère de ce capitaine l'a sauvé en donnant sa vie pour lui.",
      'Il a formé une alliance avec un rival pour défaire un Empereur.',
      'Son fruit lui permet de créer des zones où il contrôle tout.',
      "Il a vaincu une Empereur avec l'aide d'un autre capitaine à Wano.",
      'Son sous-marin jaune est reconnaissable entre mille.',
      'Capitaine des Heart Pirates, sa prime dépasse les 3 milliards.',
    ],
  },
  {
    name: 'Donquixote Doflamingo (Joker)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Né dans la plus haute noblesse, sa famille a choisi de vivre parmi les communs.',
      'Persécuté pour ses origines, il a tué son propre père par vengeance.',
      'Rejeté quand il a voulu revenir parmi les siens, il a juré de tout détruire.',
      "Il a pris le contrôle d'un royaume en manipulant son roi comme une marionnette.",
      "Il gérait le marché noir d'armes et de fruits artificiels pour un Empereur.",
      'Son fruit lui permet de créer des fils quasi-invisibles et indestructibles.',
      'Il a été vaincu et emprisonné après avoir régné par la terreur.',
      'Ancien roi de Dressrosa et fournisseur de Kaido.',
    ],
  },
  {
    name: 'Gecko Moria (Le Maître des Ombres)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Son équipage entier a été massacré par un Empereur il y a des années.',
      'Traumatisé, il a décidé de créer une armée qui ne peut pas mourir.',
      'Il a établi son territoire sur un navire géant dans une zone brumeuse.',
      "Il a volé l'ombre d'un futur Empereur et l'a placée dans un géant.",
      'Après une grande guerre, il a été ciblé par ses anciens alliés.',
      'On le croyait mort mais il est réapparu avec un autre Empereur.',
      'Son fruit lui permet de voler et manipuler les ombres.',
      'Son rire distinctif est "Kishishishi", connu pour sa paresse.',
    ],
  },
  {
    name: 'Baggy le Clown (Le Génie du Crime)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Il était mousse sur le navire du seul homme à avoir trouvé le trésor ultime.',
      'Il a mangé son fruit par accident, perdant à jamais la capacité de nager.',
      "Sa chance insolente et ses connexions l'ont propulsé au sommet.",
      "Il s'est échappé de la prison la plus sécurisée du monde avec un futur Empereur.",
      "Des subordonnés compétents l'ont rejoint, gonflant sa réputation.",
      "Il est devenu la figure de proue d'une organisation puissante par accident.",
      'Son fruit lui permet de fragmenter son corps en morceaux volants.',
      'Devenu Empereur malgré lui, reconnaissable à son nez rouge.',
    ],
  },
  {
    name: 'Edward Weevil (Le Fils de Barbe Blanche)',
    type: 'pirate',
    difficulty: 3,
    hints: [
      'Sa mère affirme avoir eu une relation avec un Empereur il y a 40 ans.',
      "Sa force physique est comparée à celle d'une légende dans sa jeunesse.",
      'Il a massacré de nombreux équipages pour trouver un "héritage".',
      'Malgré sa puissance, son intelligence semble très limitée.',
      'Il est entièrement manipulé par sa mère qui le dirige.',
      'Il a attaqué l\'île où vivaient les anciens alliés de son "père".',
      "Sa moustache en croissant imite celle de celui qu'il prétend être son père.",
      'Il prétend être le fils biologique de Barbe Blanche.',
    ],
  },

  // ==================== MARINES ====================
  {
    name: 'Monkey D. Garp (Le Poing / Le Héros de la Marine)',
    type: 'marine',
    difficulty: 1,
    hints: [
      'Il a combattu le Roi des Pirates de nombreuses fois, développant un respect mutuel.',
      'Il a refusé plusieurs fois le plus haut grade par choix personnel.',
      'Le Roi des Pirates lui a confié la protection de son fils à naître.',
      "Son propre fils est devenu l'ennemi numéro un du Gouvernement.",
      'Il entraînait les enfants en les jetant dans des jungles ou des ravins.',
      'Ses poings nus ont vaincu des légendes sans aucun pouvoir spécial.',
      "Il est le grand-père d'un des Empereurs actuels.",
      'Héros légendaire de la Marine, père adoptif du fils de Roger.',
    ],
  },
  {
    name: 'Sengoku le Bouddha',
    type: 'marine',
    difficulty: 2,
    hints: [
      "Il fait partie d'un trio légendaire avec deux autres héros de son époque.",
      'Il a caché un secret de naissance pendant des années pour éviter une guerre.',
      "Il a élevé un orphelin comme son propre fils après l'avoir recueilli.",
      'Il a dirigé toutes les forces navales pendant la plus grande guerre maritime.',
      'Dégoûté par les événements, il a démissionné de son poste suprême.',
      'Son fruit mythique lui permet de devenir un géant doré.',
      'Il est resté comme Inspecteur Général après son départ.',
      'Ancien Amiral en Chef, il précédait Akainu à ce poste.',
    ],
  },
  {
    name: 'Sakazuki (Akainu)',
    type: 'marine',
    difficulty: 1,
    hints: [
      'Partisan de la Justice Absolue, il est prêt à tout pour éliminer le mal.',
      'Il a détruit un navire de civils "au cas où" un criminel s\'y cacherait.',
      'Il a exécuté des soldats de son propre camp qui fuyaient par lâcheté.',
      'Il a tué le fils de Roger en transperçant sa poitrine.',
      'Il a affronté un rival pendant 10 jours pour le poste suprême.',
      "Sa victoire a changé le climat d'une île de façon permanente.",
      "Son fruit lui donne le pouvoir du magma, l'un des plus destructeurs.",
      'Actuel Amiral en Chef de la Marine.',
    ],
  },
  {
    name: 'Kuzan (Aokiji)',
    type: 'marine',
    difficulty: 1,
    hints: [
      "Un héros l'a sauvé dans sa jeunesse, façonnant sa vision de la justice.",
      "Il a laissé une criminelle recherchée s'échapper il y a 20 ans.",
      'Il privilégie une approche paresseuse, agissant quand il le juge nécessaire.',
      "Il a perdu sa jambe lors d'un duel de 10 jours pour le poste suprême.",
      'Après sa défaite, il a quitté son organisation et rejoint un Empereur.',
      'Son fruit lui permet de créer et devenir de la glace.',
      "Il a gelé une partie de l'océan pour aider une évacuation.",
      'Ancien Amiral qui a démissionné après avoir perdu contre Akainu.',
    ],
  },
  {
    name: 'Borsalino (Kizaru)',
    type: 'marine',
    difficulty: 2,
    hints: [
      'Son attitude décontractée contraste avec sa puissance dévastatrice.',
      'Il parle de manière traînante et semble rarement pressé ou inquiet.',
      'Il a vaincu plusieurs pirates prometteurs sans le moindre effort.',
      "Il a proposé d'aller seul régler un problème impliquant deux Empereurs.",
      'Son style de combat repose sur des coups de pied à vitesse extrême.',
      'Il peut créer des épées et des lasers avec son pouvoir.',
      'Son fruit lui permet de devenir et contrôler la lumière.',
      "L'un des trois Amiraux actuels, connu pour sa nonchalance.",
    ],
  },
  {
    name: 'Issho (Fujitora)',
    type: 'marine',
    difficulty: 2,
    hints: [
      "Il s'est volontairement privé de la vue pour ne plus voir les injustices.",
      'Recruté directement au plus haut grade militaire par conscription.',
      'Il croit en une justice plus humaine et questionne le Gouvernement.',
      "Il s'est incliné publiquement pour s'excuser des crimes d'un pirate.",
      "Il a proposé l'abolition d'un système lors d'une réunion mondiale.",
      "Il a interdit certains pirates d'entrer dans les territoires sous sa garde.",
      'Son fruit lui permet de contrôler la gravité, invoquant des météorites.',
      'Amiral aveugle, il utilise une canne-épée pour se battre.',
    ],
  },
  {
    name: 'Aramaki (Ryokugyu)',
    type: 'marine',
    difficulty: 2,
    hints: [
      "Il n'a pas mangé depuis trois ans grâce à ses capacités spéciales.",
      "Il admire profondément l'Amiral en Chef et partage sa vision de la justice.",
      'Il a vaincu seul deux commandants affaiblis après une grande bataille.',
      "Il s'est rendu dans un pays sans autorisation pour capturer un Empereur.",
      "Il a reculé face à la menace d'un Empereur depuis son navire au large.",
      'Son fruit lui permet de créer et contrôler des plantes.',
      "Il peut absorber les nutriments de tout ce qu'il touche.",
      'Le dernier Amiral présenté, il représente la Justice Absolue.',
    ],
  },
  {
    name: 'Smoker (Le Chasseur Blanc)',
    type: 'marine',
    difficulty: 1,
    hints: [
      'Il était stationné dans la ville où le Roi des Pirates a été exécuté.',
      'Il a été le premier de son rang à vraiment poursuivre un futur Empereur.',
      "Son obsession l'a mené à travers le monde entier.",
      "Il s'est temporairement allié avec des pirates contre un scientifique fou.",
      'Il utilise une arme en Granit Marin qui annule les pouvoirs.',
      'Son fruit lui permet de créer et devenir de la fumée.',
      'Il est reconnaissable à ses deux cigares permanents.',
      'Vice-Amiral obsédé par la capture de Luffy.',
    ],
  },
  {
    name: 'Tashigi',
    type: 'marine',
    difficulty: 2,
    hints: [
      'Elle est passionnée par les épées et rêve de les récupérer des criminels.',
      "Elle ressemble étrangement à une amie d'enfance décédée d'un pirate.",
      "Cette ressemblance perturbe ce pirate chaque fois qu'ils s'affrontent.",
      "Elle a été outrée par des expériences sur des enfants qu'elle a découvertes.",
      'Elle porte des lunettes et est connue pour sa maladresse occasionnelle.',
      'Elle a été promue plusieurs fois en suivant son supérieur.',
      'Son épée actuelle est un Meito de qualité.',
      'Subordonnée de Smoker, elle est une épéiste déterminée.',
    ],
  },
  {
    name: 'Koby (Le Héros)',
    type: 'marine',
    difficulty: 1,
    hints: [
      "Il a été le premier ami du futur Roi des Pirates au début de l'aventure.",
      "Accidentellement devenu serviteur d'une pirate, il rêvait d'un autre destin.",
      "Un pirate l'a aidé à s'échapper et l'a encouragé à poursuivre son rêve.",
      "Lors d'une grande guerre, son cri a éveillé une capacité rare en lui.",
      'Il a osé se dresser devant un Amiral pour arrêter un massacre.',
      "Il a développé une technique de frappe avancée après des années d'entraînement.",
      "Il s'est entraîné sous un héros légendaire.",
      "L'une des étoiles montantes de la Marine, ami d'enfance de Luffy.",
    ],
  },
  {
    name: 'Helmeppo',
    type: 'marine',
    difficulty: 2,
    hints: [
      "Fils d'un officier corrompu, il abusait de sa position pour terroriser.",
      'Son père utilisait un loup de compagnie pour maintenir son emprise.',
      'Après la défaite de son père, il a été forcé de changer de vie.',
      "Sa transformation d'enfant gâté à combattant respectable est remarquable.",
      "Il s'est entraîné sous un héros aux côtés d'un autre jeune marine.",
      'Il utilise deux kukris comme armes principales.',
      "Il est souvent vu aux côtés de son partenaire d'entraînement.",
      'Fils du capitaine Morgan, maintenant Lieutenant-Commander.',
    ],
  },
  {
    name: 'Tsuru (La Grande Conseillère)',
    type: 'marine',
    difficulty: 3,
    hints: [
      'Elle fait partie de la même génération que deux autres héros légendaires.',
      "Un futur roi criminel préférait fuir plutôt que l'affronter.",
      'Son pouvoir peut temporairement "nettoyer" le mal des cœurs.',
      'Elle est connue pour son esprit stratégique et sa sagesse.',
      "Elle a poursuivi un criminel pendant des années sans l'attraper.",
      'Elle peut "laver" les gens et les accrocher comme du linge.',
      'Malgré son âge avancé, elle reste respectée au plus haut niveau.',
      'Vice-Amirale depuis des décennies, conseillère respectée.',
    ],
  },
  {
    name: 'Sentomaru',
    type: 'marine',
    difficulty: 3,
    hints: [
      "Il se considère comme l'homme à la garde la plus impénétrable.",
      'Il était le garde du corps personnel du plus grand génie du monde.',
      'Il commande des unités robotiques au combat avec efficacité.',
      'Son style de combat est basé sur le sumo, utilisant des frappes de paume.',
      'Il maîtrise une technique avancée sans avoir mangé de fruit.',
      'Il porte une armure de style japonais et une hache géante.',
      "Il a affronté des pirates prometteurs aux côtés d'un Amiral.",
      'Officier de la Marine, ancien garde de Vegapunk.',
    ],
  },

  // ==================== RÉVOLUTIONNAIRES ====================
  {
    name: 'Monkey D. Dragon (Le Révolutionnaire)',
    type: 'revolutionary',
    difficulty: 2,
    hints: [
      "Fils d'un héros légendaire, il a choisi une voie opposée à son père.",
      "Il a fondé une armée pour renverser l'ordre mondial établi.",
      "Il est apparu dans une ville célèbre pour sauver quelqu'un d'important.",
      "Le pouvoir mondial le considère comme l'homme le plus dangereux.",
      'Il a recueilli et élevé un noble qui avait fui sa famille.',
      'Ses pouvoirs semblent liés au vent et aux tempêtes.',
      'Son tatouage facial et son capuchon sont distinctifs.',
      "Père de Luffy et leader de l'Armée Révolutionnaire.",
    ],
  },
  {
    name: "Sabo (L'Officier en Chef / La Flamme de la Révolution)",
    type: 'revolutionary',
    difficulty: 1,
    hints: [
      'Né noble, il a fui sa famille pour vivre avec deux frères adoptifs.',
      "Ses parents l'ont forcé à revenir le jour où un noble suprême visitait.",
      'Son navire a été détruit par ce noble, le laissant pour mort.',
      "Il a vécu avec une amnésie totale jusqu'à la mort d'un de ses frères.",
      "Il a hérité d'un pouvoir de feu lors d'un tournoi dans un colisée.",
      "Son arme est un tuyau en métal qu'il utilisait déjà enfant.",
      'Il porte les trois coupes de saké de fraternité en tatouage.',
      "Frère adoptif de Luffy et Ace, numéro deux de l'Armée Révolutionnaire.",
    ],
  },
  {
    name: 'Emporio Ivankov (La Reine des Okamas)',
    type: 'revolutionary',
    difficulty: 2,
    hints: [
      'Il dirige un royaume sur une île depuis des années.',
      'Il gérait un paradis secret dans une prison pendant sa détention.',
      'Il peut changer le sexe des gens, les guérir ou les booster.',
      'Il a sauvé un futur Empereur de la mort en injectant des hormones.',
      "Il est un commandant d'une armée rebelle et ami proche de son leader.",
      'Son visage massif et son maquillage sont reconnaissables.',
      'Il peut faire des "Death Winks" dévastateurs avec ses cils.',
      "Son fruit lui permet d'injecter des hormones qui modifient le corps.",
    ],
  },
  {
    name: 'Inazuma',
    type: 'revolutionary',
    difficulty: 3,
    hints: [
      'Son apparence change radicalement selon sa forme du moment.',
      'Il/Elle boit souvent du vin et reste généralement calme en combat.',
      "Il/Elle peut couper n'importe quoi et le manipuler comme du papier.",
      'Dans une prison, il/elle a créé un pont de pierre découpée.',
      'Sa coiffure est bicolore, orange et blanche, quelle que soit sa forme.',
      "Il/Elle est proche d'un commandant excentrique de son organisation.",
      'Son fruit transforme ses mains en ciseaux géants.',
      'Commandant révolutionnaire qui peut être homme ou femme.',
    ],
  },
  {
    name: 'Koala',
    type: 'revolutionary',
    difficulty: 2,
    hints: [
      'Ancienne esclave, elle souriait constamment même terrifiée par réflexe.',
      "Celui qui l'a libérée l'a raccompagnée chez elle, causant sa propre mort.",
      'Elle a rejoint une armée rebelle après avoir compris les injustices.',
      "Elle est experte dans un art martial qu'elle a appris d'un maître.",
      'Elle travaille souvent avec le numéro deux de son organisation.',
      'Elle reste généralement optimiste mais peut devenir violente.',
      "Fisher Tiger l'a libérée lors de son raid sur Marie-Joie.",
      "Instructrice au sein de l'Armée Révolutionnaire.",
    ],
  },
  {
    name: 'Karasu',
    type: 'revolutionary',
    difficulty: 3,
    hints: [
      "Il parle si doucement qu'il a besoin d'un amplificateur.",
      'Il peut espionner, attaquer ou transporter des personnes avec son pouvoir.',
      "Il a participé à une opération de sauvetage lors d'une réunion mondiale.",
      'Son apparence est sombre avec un masque couvrant son visage.',
      "Sa capacité d'infiltration en fait un agent précieux.",
      'Il commande une division régionale de son organisation.',
      "Son fruit lui permet de se transformer en une nuée d'oiseaux noirs.",
      "Commandant du Nord de l'Armée Révolutionnaire.",
    ],
  },

  // ==================== SUPERNOVAS / WORST GENERATION ====================
  {
    name: 'Eustass "Captain" Kid',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Il a perdu son bras lors d'une confrontation avec un Empereur.",
      'Sa méthode brutale lui a valu une prime supérieure à un rival avant un tournant.',
      "Il a formé une alliance qui a été trahie par l'un de ses membres.",
      "À Wano, il s'est allié avec son rival contre un ennemi commun.",
      'Avec un autre capitaine, il a vaincu une Empereur femme.',
      "Son fruit lui permet d'attirer et repousser le métal comme un aimant.",
      'Sa prime actuelle est de 3 milliards après les événements de Wano.',
      'Capitaine aux cheveux rouges avec un bras mécanique.',
    ],
  },
  {
    name: 'Killer (Le Massacreur)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      "Ami d'enfance de son capitaine, ils ont fondé leur groupe ensemble.",
      "Il porte un masque car il déteste qu'on voie son visage quand il rit.",
      'Il a été forcé de manger un fruit défectueux qui le fait rire sans arrêt.',
      'Il utilise des lames rotatives attachées à ses bras.',
      "Sous un autre nom, il a servi un tyran avant d'être libéré.",
      "Il est l'un des rares non-capitaines de sa génération notoire.",
      "Le fruit défectueux l'a privé de sa capacité à nager sans lui donner de pouvoir.",
      'Second de Kid, connu pour sa brutalité au combat.',
    ],
  },
  {
    name: 'Jewelry Bonney (La Gloutonne)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Son appétit est légendaire - elle peut manger des quantités astronomiques.',
      'Elle a une connexion profonde avec un ancien roi devenu arme.',
      'Elle a infiltré le palais du pouvoir mondial pour tenter un sauvetage.',
      "Elle peut prendre n'importe quel âge, d'enfant à vieillarde.",
      'Elle a voyagé avec un équipage célèbre vers une île scientifique.',
      "Sa haine du Gouvernement vient de ce qu'ils ont fait à quelqu'un qu'elle aime.",
      "Son fruit lui permet de manipuler l'âge de n'importe qui.",
      'Capitaine pirate dont le père est Bartholomew Kuma.',
    ],
  },
  {
    name: 'Capone "Gang" Bege (Le Parrain)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Ancien parrain mafieux, il dirigeait plusieurs familles criminelles.',
      'Son hobby est de décapiter les organisations pour le plaisir.',
      "Il a épousé la fille d'une Empereur et a eu un fils.",
      "Il a planifié un assassinat lors d'une fête de thé avec un allié inattendu.",
      'Il peut se transformer en une structure géante défensive.',
      'Son fruit lui permet de devenir une forteresse abritant une armée.',
      'Son plan impliquait des portraits et des lance-missiles.',
      'Capitaine au style mafieux, allié temporaire des Chapeaux de Paille.',
    ],
  },
  {
    name: 'Scratchmen Apoo (La Vague du Rugissement)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Il était déjà un informateur avant de former une alliance.',
      'Il a trahi ses alliés, les livrant à un Empereur.',
      'Ses attaques touchent tous ceux qui entendent sa musique.',
      'La seule défense est de se boucher les oreilles ou être sourd.',
      'Son style musical est bruyant et agressif, comme sa personnalité.',
      'Ses membres sont plus longs que la normale à cause de son origine.',
      'Son fruit transforme son corps en instruments de musique.',
      'Capitaine de la tribu des Bras Longs, traître notoire.',
    ],
  },
  {
    name: 'X Drake (Le Drapeau Rouge)',
    type: 'marine',
    difficulty: 2,
    hints: [
      "Fils d'un Marine devenu pirate, il a eu une enfance traumatisante.",
      'Son père travaillait avec un futur roi criminel avant de le trahir.',
      'Il a rejoint une organisation secrète de son vrai camp.',
      "Il s'est infiltré chez un Empereur en se faisant passer pour un pirate.",
      "À Wano, il a révélé sa vraie allégeance et aidé l'alliance.",
      'Il utilise une épée et une hache à quatre lames.',
      'Son fruit ancien lui permet de se transformer en Allosaurus.',
      'Membre de SWORD, agent infiltré chez les Cent Bêtes.',
    ],
  },
  {
    name: 'Basil Hawkins (Le Magicien)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      "Il utilise des cartes de tarot pour prédire l'avenir et décider.",
      'Il a rejoint un Empereur après que ses cartes lui aient prédit la mort.',
      'Il peut stocker des "vies" d\'autres personnes pour se protéger.',
      'À Wano, il a utilisé un allié comme bouclier contre son ami.',
      "Ses lectures l'ont parfois trompé sur l'issue des événements.",
      'Son apparence inclut des cheveux blonds et un air stoïque.',
      'Son fruit lui permet de créer des poupées vaudou transférant les dégâts.',
      "Capitaine qui lit l'avenir, vaincu à Wano.",
    ],
  },
  {
    name: 'Urouge (Le Moine Fou)',
    type: 'pirate',
    difficulty: 3,
    hints: [
      "C'est un moine guerrier d'une religion inconnue.",
      "Il est le seul de sa génération à avoir vaincu un commandant d'Empereur.",
      "Cette victoire lui a valu d'être pourchassé par un autre commandant.",
      'Plus il est blessé, plus il devient grand et puissant.',
      'Il a survécu à une rencontre avec une Empereur sur une île céleste.',
      "Son arme est un pilier géant qu'il manie comme une massue.",
      'Son fruit convertit les dégâts reçus en force physique.',
      "Capitaine originaire d'une île céleste.",
    ],
  },

  // ==================== ROYAUME DE WANO ====================
  {
    name: 'Kozuki Oden',
    type: 'civilian',
    difficulty: 1,
    hints: [
      "Héritier d'un shogunat, il était considéré comme un fauteur de troubles.",
      'Il a créé un groupe de samouraïs légendaires qui lui étaient dévoués.',
      'Il a voyagé avec les équipages de deux Empereurs différents.',
      'Il était le seul de son temps à pouvoir lire et graver une écriture ancienne.',
      'Trahi par des conspirateurs, il a été exécuté après avoir bouilli pendant une heure.',
      'Ses derniers mots ont inspiré une rébellion 20 ans plus tard.',
      "Il portait deux épées légendaires maintenant entre d'autres mains.",
      "Daimyo de Kuri, il a voyagé avec Roger jusqu'à Laugh Tale.",
    ],
  },
  {
    name: 'Kozuki Momonosuke',
    type: 'civilian',
    difficulty: 2,
    hints: [
      "Fils d'une légende, il a été envoyé 20 ans dans le futur pour survivre.",
      'Enfant, il a mangé par accident un fruit artificiel créé par un génie.',
      "Une alliée l'a vieilli de 20 ans pour qu'il puisse combattre.",
      "En utilisant son pouvoir, il a porté un allié jusqu'au champ de bataille final.",
      "Il a hérité de la capacité d'entendre une voix que peu peuvent percevoir.",
      "Après la victoire, il est devenu dirigeant à l'âge biologique de 8 ans.",
      'Son fruit lui permet de se transformer en dragon rose.',
      "Actuel Shogun de Wano, fils d'Oden.",
    ],
  },
  {
    name: "Yamato (Fils autoproclamé d'Oden)",
    type: 'pirate',
    difficulty: 1,
    hints: [
      "Enfant d'un Empereur, élevé(e) dans une forteresse depuis sa naissance.",
      "Après avoir lu un journal, elle a décidé de porter l'héritage d'un héros mort.",
      "Son parent l'a enchaîné(e) avec des menottes explosives pour l'empêcher de fuir.",
      'Elle a protégé un enfant et un journal pendant 20 ans en secret.',
      'Elle maîtrise une capacité royale héritée de son parent.',
      'Elle voulait partir en mer mais a choisi de protéger son pays.',
      "Son fruit mythique lui donne la forme d'un loup divin.",
      "Enfant de Kaido qui s'identifie comme Oden.",
    ],
  },
  {
    name: "Shimotsuki Ryuma (Le Dieu de l'Épée)",
    type: 'civilian',
    difficulty: 3,
    hints: [
      'Il a vécu il y a des siècles, devenant une légende de son pays.',
      'Il a tranché un dragon dans le ciel, protégeant une capitale.',
      'Après sa mort, son corps et son épée ont été volés et amenés ailleurs.',
      "Un pirate a réanimé son cadavre avec l'ombre d'un squelette musicien.",
      "Un épéiste l'a vaincu et a hérité de son épée en signe de respect.",
      "Il est un ancêtre du village où un futur grand épéiste s'est entraîné.",
      'Son corps momifié portait Shusui, une épée légendaire.',
      'Légendaire samouraï de Wano, tueur de dragon.',
    ],
  },
  {
    name: 'Kurozumi Orochi',
    type: 'civilian',
    difficulty: 2,
    hints: [
      "Descendant d'une famille de traîtres exécutés et déshonorés.",
      'Il a grandi dans la haine, planifiant sa vengeance sur tout un pays.',
      'Il a conspiré avec un Empereur pour assassiner un héros et prendre le pouvoir.',
      'Chaque partie de lui peut être coupée sans le tuer définitivement.',
      'Il a régné avec terreur et famine pendant 20 ans.',
      'Trahi par son allié Empereur, il a survécu plusieurs fois.',
      'Son fruit lui permet de devenir un serpent à huit têtes.',
      'Ancien Shogun usurpateur de Wano, tué par un de ses serviteurs.',
    ],
  },
  {
    name: "Kin'emon (Kin'emon le Renard de Feu)",
    type: 'civilian',
    difficulty: 2,
    hints: [
      'Ancien voyou devenu samouraï après avoir été sauvé par son seigneur.',
      "Il est le leader d'un groupe de serviteurs dévoués.",
      "Il détestait les pirates jusqu'à ce qu'il voyage avec certains.",
      "Il a été envoyé 20 ans dans le futur avec d'autres serviteurs.",
      'Son style de combat utilise des flammes créées par son épée.',
      "Sa femme l'a attendu deux décennies sans savoir s'il était vivant.",
      'Son fruit lui permet de créer des déguisements à partir de feuilles.',
      'Leader des Neuf Fourreaux Rouges, il a orchestré la rébellion de Wano.',
    ],
  },

  // ==================== ALABASTA ====================
  {
    name: 'Nefertari Vivi',
    type: 'civilian',
    difficulty: 1,
    hints: [
      'Elle a infiltré une organisation criminelle pour découvrir qui menaçait son pays.',
      'Sa famille a refusé de rejoindre les nobles suprêmes il y a 800 ans.',
      "Elle a voyagé avec des pirates qu'elle considère comme ses amis.",
      "Elle a choisi de rester dans son pays plutôt que de continuer l'aventure.",
      "Son signal d'amitié est un X marqué sur l'avant-bras.",
      'Son compagnon est un canard coureur super rapide.',
      'Après une réunion mondiale, sa disparition a fait les gros titres.',
      "Princesse d'Alabasta, amie des Chapeaux de Paille.",
    ],
  },
  {
    name: 'Nefertari Cobra',
    type: 'civilian',
    difficulty: 2,
    hints: [
      'Il a gouverné son pays avec sagesse pendant des décennies.',
      'Il a élevé sa fille seul après la mort de sa femme.',
      'Sa famille est la seule des fondateurs à avoir refusé un privilège suprême.',
      "Il souffrait d'une maladie qui le faisait décliner progressivement.",
      "Lors d'une réunion mondiale, il a questionné les dirigeants sur l'histoire.",
      'Il a été tué dans des circonstances mystérieuses, Sabo accusé officiellement.',
      'Sa mort a provoqué une crise internationale.',
      "Roi d'Alabasta, père de Vivi, mort au Reverie.",
    ],
  },

  // ==================== ÎLE DES HOMMES-POISSONS ====================
  {
    name: 'Fisher Tiger (Le Libérateur)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      "Ancien esclave, il s'est échappé seul du palais des nobles suprêmes.",
      'Il est retourné à ce palais pour libérer tous les esclaves, pas seulement les siens.',
      'Il a fondé un équipage pour protéger son peuple des esclavagistes.',
      "Tous ses membres portent un symbole cachant les marques d'esclave.",
      'Il a libéré trois sœurs qui deviendraient des impératrices.',
      "Blessé mortellement, il a refusé une transfusion d'un certain type de sang.",
      'Sa mort a inspiré deux voies opposées parmi les siens.',
      'Homme-poisson légendaire qui a escaladé la Red Line seul.',
    ],
  },
  {
    name: 'Arlong (Arlong le Requin-Scie)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      "La mort d'un héros et une trahison l'ont radicalisé dans sa haine.",
      'Il a quitté son équipage original par désaccord avec son nouveau capitaine.',
      "Il s'est installé dans une mer faible pour terroriser les villages côtiers.",
      'Il a exploité une jeune fille pendant huit ans, la forçant à voler pour lui.',
      "Son QG imitait l'architecture de son lieu de naissance.",
      "Un futur Empereur l'a vaincu en détruisant une pièce symbolique.",
      'Sa victime la plus connue est devenue navigatrice de cet Empereur.',
      'Homme-poisson requin-scie, premier grand ennemi des Chapeaux de Paille.',
    ],
  },
  {
    name: 'Hody Jones',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Il a grandi dans un quartier pauvre, absorbant la haine environnante.',
      "Il n'a jamais personnellement souffert des humains mais les hait par éducation.",
      'Il a assassiné une reine pacifiste pour empêcher la réconciliation.',
      'Il a utilisé des pilules qui drainent la force vitale pour se renforcer.',
      "Ces pilules l'ont finalement transformé en vieillard.",
      'Il a tenté de prendre le contrôle de son île par la force.',
      'Vaincu, il est maintenant un prisonnier affaibli et âgé.',
      'Ancien capitaine dont la haine était héritée, pas vécue.',
    ],
  },

  // ==================== SKY ISLAND ====================
  {
    name: 'Enel (Le Dieu de Skypiea)',
    type: 'civilian',
    difficulty: 1,
    hints: [
      'Il a détruit sa propre île natale après avoir obtenu son pouvoir.',
      "Il s'est proclamé divinité après avoir vaincu le dirigeant précédent.",
      'Il peut entendre les pensées et voix sur tout son territoire.',
      "Son ennemi naturel est quelqu'un dont le corps est isolant.",
      "Son but était de rejoindre un astre qu'il considérait comme un paradis.",
      'Il a réussi son objectif et vit maintenant avec des automates.',
      'Son fruit lui donne le pouvoir de la foudre.',
      "Auto-proclamé dieu, il possédait l'un des fruits les plus puissants.",
    ],
  },
  {
    name: 'Wyper (Le Guerrier Shandian)',
    type: 'civilian',
    difficulty: 3,
    hints: [
      "Descendant d'un grand guerrier, il porte le poids de 400 ans de guerre.",
      'Il est le leader de guerriers qui se battent pour leur terre ancestrale.',
      'Il possède une arme qui renvoie 10 fois la force absorbée.',
      "Cette arme est si dangereuse qu'elle blesse gravement l'utilisateur.",
      "Il a temporairement arrêté le cœur d'un auto-proclamé dieu.",
      "Après la victoire, il a fait la paix avec d'anciens ennemis.",
      'Il utilise des Dials de combat et des bazookas.',
      'Guerrier qui a combattu pour récupérer la terre de son peuple.',
    ],
  },

  // ==================== DRESSROSA ====================
  {
    name: 'Kyros (Le Gladiateur Imbattable)',
    type: 'civilian',
    difficulty: 2,
    hints: [
      "Ancien criminel devenu le plus grand combattant d'un colisée légendaire.",
      'Il a remporté 3000 combats sans jamais être touché.',
      'Un roi lui a donné une chance, et il est devenu capitaine de sa garde.',
      "Il a épousé une princesse et a eu une fille qu'il a dû abandonner.",
      'Transformé par un pouvoir, tous les souvenirs de lui ont été effacés.',
      "Pendant 10 ans, il a protégé sa fille sans qu'elle sache qui il était.",
      'Redevenu lui-même, il a été le premier à frapper le tyran.',
      'Gladiateur de Dressrosa qui a sacrifié une jambe pour sa famille.',
    ],
  },
  {
    name: 'Rebecca (La Princesse Impertinente)',
    type: 'civilian',
    difficulty: 2,
    hints: [
      "Petite-fille d'un roi, sa mère a été tuée par un pirate cruel.",
      "Elle a été élevée par un jouet sans savoir que c'était son père.",
      'Elle a été forcée de combattre dans une arène comme gladiatrice.',
      'Son style de combat évite de blesser, utilisant la vitesse pour esquiver.',
      'Les habitants la méprisaient à cause de la propagande du tyran.',
      "Après la libération, elle est reconnue comme ce qu'elle est vraiment.",
      'Elle a retrouvé son père après 10 ans de séparation.',
      'Gladiatrice de Dressrosa, fille de Kyros.',
    ],
  },

  // ==================== BAROQUE WORKS ====================
  {
    name: 'Daz Bonez (Mr. 1)',
    type: 'pirate',
    difficulty: 3,
    hints: [
      'Ancien assassin surnommé pour sa létalité avant de rejoindre une organisation.',
      "Il était l'agent masculin le plus haut gradé sous un certain numéro.",
      "Son combat a forcé un épéiste à apprendre à couper l'acier.",
      'Après la défaite de son organisation, il a été emprisonné.',
      "Il s'est échappé avec son ancien chef et a participé à une grande guerre.",
      'Il suit maintenant son ancien chef dans une nouvelle organisation.',
      "Son fruit transforme n'importe quelle partie de son corps en lame.",
      'Ancien Mr. 1, son corps entier est une arme tranchante.',
    ],
  },
  {
    name: 'Bentham (Mr. 2 Bon Clay)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Il travaillait seul dans une organisation criminelle, sans partenaire.',
      "Il s'est lié d'amitié avec des ennemis malgré leur affrontement.",
      "Il s'est sacrifié pour permettre à des amis de s'échapper.",
      'Emprisonné, il a aidé un futur Empereur à trouver un allié.',
      "Il s'est sacrifié une seconde fois pour permettre une évasion massive.",
      'Il a survécu et dirige maintenant un paradis secret dans une prison.',
      'Son fruit lui permet de copier le visage et le corps de quiconque.',
      'Okama au grand cœur, son amitié transcende les camps.',
    ],
  },

  // ==================== SCIENTIFIQUES & AUTRES ====================
  {
    name: 'Vegapunk (Le Génie)',
    type: 'civilian',
    difficulty: 1,
    hints: [
      'Né sur une île hivernale, son génie dépassait les ressources de son village.',
      "Il a fait partie d'un groupe de scientifiques illégaux avant d'être capturé.",
      "Le Gouvernement l'a recruté comme scientifique en chef.",
      "Son cerveau est devenu si grand qu'il a dû le stocker ailleurs.",
      "Il s'est divisé en six versions représentant différents aspects de lui-même.",
      'Il a découvert comment fonctionnent les fruits du démon.',
      "Ses inventions ont 500 ans d'avance sur leur temps.",
      'Le plus grand génie du monde, créateur des Pacifistas.',
    ],
  },
  {
    name: 'Caesar Clown (Le Scientifique Fou)',
    type: 'civilian',
    difficulty: 2,
    hints: [
      'Ancien collègue du plus grand génie, il était jaloux de sa réputation.',
      'Il a causé une explosion qui a tué de nombreux collègues.',
      'Il travaillait pour un roi criminel en créant des armes et des drogues.',
      'Il expérimentait sur des enfants kidnappés avec des substances addictives.',
      'Capturé par des pirates, il a été forcé de les aider plusieurs fois.',
      'Il a créé un antidote pour des armes chimiques à Wano.',
      'Son fruit lui permet de créer et contrôler tous les types de gaz.',
      'Scientifique lâche qui a travaillé pour plusieurs Empereurs.',
    ],
  },
  {
    name: 'Vinsmoke Judge (Le Roi de Germa)',
    type: 'civilian',
    difficulty: 2,
    hints: [
      "Ancien membre d'un groupe de scientifiques illégaux dans sa jeunesse.",
      'Il a fondé un royaume militaire sans territoire fixe.',
      'Il a modifié génétiquement ses enfants pour en faire des soldats.',
      "Un de ses fils est le seul à avoir gardé ses émotions, ce qu'il a rejeté.",
      "Il a tenté de marier ce fils à la fille d'une Empereur.",
      'Son armée utilise des clones et des combinaisons technologiques.',
      "Il a finalement reconnu la valeur du fils qu'il avait rejeté.",
      'Roi de Germa 66 et père de Sanji.',
    ],
  },
  {
    name: 'Silvers Rayleigh (Le Roi Sombre)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Vivant sur un bateau volé, il a été invité à "renverser le monde".',
      "Il était le premier membre de l'équipage du seul Roi des Pirates.",
      "Après la dissolution de cet équipage, il s'est retiré comme artisan.",
      'Il a sauvé des pirates prometteurs face à un Amiral et des robots.',
      'Il a entraîné un futur Empereur pendant deux ans sur une île.',
      'Il peut nager dans des eaux infestées de monstres marins.',
      "Son surnom vient de son statut de bras droit d'un roi.",
      'Second de Gol D. Roger, maître de Haki.',
    ],
  },
  {
    name: 'Gol D. Roger (Le Roi des Pirates)',
    type: 'pirate',
    difficulty: 1,
    hints: [
      'Né dans la ville où il mourrait également des décennies plus tard.',
      'Il a formé son équipage après avoir trouvé son futur second sur un bateau.',
      "Atteint d'une maladie incurable, il a fait un dernier voyage.",
      'Il a demandé à un rival Marine de protéger son fils à naître.',
      "Il est le seul à avoir atteint l'île finale et découvert la vérité.",
      'Ses dernières paroles ont lancé une ère entière de piraterie.',
      'Son trésor est toujours recherché par des milliers de pirates.',
      'Le seul à avoir porté le titre suprême de la piraterie.',
    ],
  },

  // ==================== PERSONNAGES ADDITIONNELS ====================
  {
    name: 'Perona (La Princesse Fantôme)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Elle a grandi seule, trouvant du réconfort dans les peluches et le gothique.',
      'Elle a été recueillie par un pirate et est devenue commandante.',
      'Les personnes touchées par son pouvoir deviennent extrêmement déprimées.',
      "Un tireur l'a vaincue car il était déjà naturellement négatif.",
      'Envoyée loin par un pouvoir, elle a vécu deux ans dans un château lugubre.',
      'Elle a soigné à contrecœur un épéiste pendant son entraînement.',
      'Son fruit crée des fantômes qui drainent la volonté de vivre.',
      'Ancienne commandante de Thriller Bark au style gothique-lolita.',
    ],
  },
  {
    name: 'Donquixote Rosinante (Corazon)',
    type: 'marine',
    difficulty: 2,
    hints: [
      "Frère cadet d'un futur roi criminel, il a fui avec lui dans l'enfance.",
      "Traumatisé par la violence de son frère, il s'est enfui et a été recueilli.",
      "Il a infiltré l'équipage de son frère en tant qu'agent secret.",
      "Son nom de code correspondait au siège du Cœur dans l'organisation.",
      'Il a sauvé un enfant malade en volant un fruit pour le guérir.',
      "Son frère l'a tué quand il a découvert sa trahison.",
      'Son fruit lui permettait de créer des zones de silence totale.',
      'Agent infiltré qui a sacrifié sa vie pour sauver Law.',
    ],
  },
  {
    name: 'Charlotte Pudding (Trois Yeux)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Son trait physique unique était source de moqueries, même de sa mère.',
      "Elle devait épouser quelqu'un pour ensuite l'assassiner.",
      "Elle est tombée amoureuse quand il a complimenté ce qu'elle haïssait.",
      "Elle a aidé des ennemis de sa famille à s'échapper.",
      "Elle a embrassé celui qu'elle aimait puis effacé ce souvenir.",
      'Elle est chocolatière de métier dans le territoire de sa mère.',
      'Son fruit lui permet de manipuler les souvenirs comme des films.',
      '35ème fille de Big Mom, elle possède un troisième œil.',
    ],
  },
  {
    name: 'Carrot',
    type: 'pirate',
    difficulty: 2,
    hints: [
      "Elle s'est cachée sur un navire pour vivre une aventure.",
      'Un allié lui a confié une mission avant de se sacrifier.',
      'Sous la lumière lunaire, elle peut atteindre une forme surpuissante.',
      'Cette forme lui donne une force électrique décuplée.',
      "Elle a aidé à combattre les forces d'une Empereur.",
      'Après les événements de Wano, elle est devenue dirigeante chez elle.',
      'Elle adore grignoter les oreilles des gens.',
      'Lapine Mink énergique qui a voyagé avec les Chapeaux de Paille.',
    ],
  },
  {
    name: 'Pedro (Le Gardien de la Baleine)',
    type: 'pirate',
    difficulty: 3,
    hints: [
      'Il cherchait une pierre ancienne pour son peuple quand il a été capturé.',
      'Une Empereur lui a pris 50 ans de vie et un œil.',
      "Il croyait fermement qu'un équipage amènerait l'aube du monde.",
      "Il a accompagné une équipe d'infiltration dans un territoire ennemi.",
      "Face à un fils aîné, il s'est sacrifié en explosant.",
      "Ses derniers mots ont chargé une amie de voir l'aube à sa place.",
      'Sa mort a profondément marqué ceux qui voyageaient avec lui.',
      "Jaguar Mink qui s'est sacrifié pour les Chapeaux de Paille.",
    ],
  },
  {
    name: 'Nekomamushi (Le Gardien de la Nuit)',
    type: 'civilian',
    difficulty: 2,
    hints: [
      'Enfant, il a quitté son foyer avec un compagnon pour voir le monde.',
      'Ils ont été réduits en esclavage puis sauvés par un équipage légendaire.',
      'Il a servi un seigneur et fait partie de ses serviteurs dévoués.',
      'Sa dispute avec son compagnon dure depuis la mort de leur maître.',
      'Il a perdu un membre en protégeant un secret sous la torture.',
      'Il maîtrise une technique électrique propre à son espèce.',
      'Il règne sur son peuple pendant les heures nocturnes.',
      "Chat Mink et l'un des deux souverains de Zou.",
    ],
  },
  {
    name: 'Inuarashi (Le Gardien du Jour)',
    type: 'civilian',
    difficulty: 2,
    hints: [
      'Avec un compagnon, il a voyagé hors de chez lui et servi un seigneur.',
      'Leur rivalité vient de leur désaccord sur la mort de leur maître.',
      'Il a perdu un membre en résistant à la torture pour garder un secret.',
      "Il fait partie d'un groupe de serviteurs dévoués à un héros mort.",
      'Il a affronté un ennemi puissant en utilisant une forme lunaire.',
      "Son style combine l'épée et une technique électrique.",
      'Il règne sur son peuple pendant les heures diurnes.',
      'Chien Mink et co-dirigeant de Zou.',
    ],
  },
  {
    name: 'Jack la Sécheresse',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Il a attaqué un peuple entier et torturé ses membres pendant cinq jours.',
      "Il a tenté de libérer un roi criminel d'un convoi et a échoué.",
      "Tombé à l'eau, il a survécu mais ne pouvait pas nager.",
      'Sa prime dépassait le milliard avant sa défaite.',
      'Il a été vaincu par des guerriers utilisant une forme lunaire.',
      'Il détruit tout sur son passage, méritant son surnom.',
      "C'est un être hybride de type poisson à défenses.",
      "L'une des trois Calamités de Kaido.",
    ],
  },
  {
    name: 'Charlotte Cracker (Le Commandant des Biscuits)',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Personne ne connaissait son vrai visage car il se cachait dans une armure.',
      'Ses créations sont assez dures pour résister à une forme avancée de combat.',
      "Un futur Empereur l'a vaincu après 11 heures en mangeant ses créations.",
      "Une alliée l'a aidé en ramollissant ses armes avec de l'eau de pluie.",
      'Sa prime de 860 millions reflétait sa dangerosité.',
      'Il gardait une zone spécifique du territoire de sa mère.',
      'Son fruit lui permet de créer des biscuits infinis.',
      '10ème fils de Big Mom, Sweet Commander.',
    ],
  },
  {
    name: 'Charlotte Smoothie',
    type: 'pirate',
    difficulty: 2,
    hints: [
      "C'est la seule femme parmi les trois plus hauts commandants de sa mère.",
      "Sa morphologie vient de l'héritage d'un peuple aux jambes longues.",
      'Elle peut absorber des liquides pour augmenter sa taille et sa force.',
      "Malgré sa puissance, elle n'a jamais eu de combat majeur montré.",
      'Elle a poursuivi des ennemis lors de leur fuite du territoire.',
      'Sa prime est la plus élevée connue pour une femme pirate.',
      "Son fruit lui permet d'essorer les liquides de tout.",
      '14ème fille de Big Mom, Sweet Commander.',
    ],
  },
  {
    name: 'Denjiro (Kyoshiro)',
    type: 'civilian',
    difficulty: 2,
    hints: [
      'Orphelin des rues, il a été recueilli par un seigneur légendaire.',
      "Il est devenu le plus intelligent et rusé d'un groupe de serviteurs.",
      'Après la mort de son maître, sa rage a transformé son apparence.',
      "Il s'est infiltré auprès d'un tyran sous une fausse identité pendant 20 ans.",
      'En tant que yakuza, il a protégé une princesse en secret.',
      "Il a révélé sa vraie identité lors d'un raid final.",
      "C'est lui qui a finalement éliminé le tyran pour de bon.",
      "L'un des Neuf Fourreaux, espion pendant deux décennies.",
    ],
  },
  {
    name: 'Kawamatsu (Le Kappa)',
    type: 'civilian',
    difficulty: 3,
    hints: [
      'Il a échoué dans un pays étranger enfant avec sa mère.',
      'Il se faisait passer pour une créature légendaire car son espèce était persécutée.',
      "Un seigneur l'a sauvé de la discrimination et il est devenu son serviteur.",
      'Après la mort de ce maître, il a collecté des armes pour une future rébellion.',
      "Il a protégé une princesse enfant avant d'être capturé.",
      'Il a survécu 13 ans en prison en mangeant du poisson empoisonné.',
      'Son style combine le sabre et des techniques de sumo.',
      'Homme-poisson des Neuf Fourreaux, surnommé pour sa couverture.',
    ],
  },
  {
    name: 'Ashura Doji (Shutenmaru)',
    type: 'civilian',
    difficulty: 3,
    hints: [
      "Autrefois le plus grand criminel d'une région, il terrorisait tous.",
      "Un seigneur l'a vaincu seul et l'a recruté comme serviteur.",
      'Après la mort de ce maître, il a abandonné son nom et vécu en bandit.',
      "Il pillait les fermes d'un Empereur par rébellion silencieuse.",
      "Il en voulait à d'autres serviteurs d'avoir voyagé dans le temps sans lui.",
      'Il a rejoint une alliance après avoir vu la détermination du leader.',
      "Il s'est sacrifié pour sauver ses camarades d'une explosion.",
      'Ancien brigand des Neuf Fourreaux.',
    ],
  },
  {
    name: 'Kiku (Kikunojo de la Neige Persistante)',
    type: 'civilian',
    difficulty: 2,
    hints: [
      "Elle s'identifie différemment de sa naissance, ce qu'elle assume pleinement.",
      "Elle est la sœur d'un ancien commandant d'un Empereur défunt.",
      "Elle a servi comme page d'un seigneur avant de devenir guerrière.",
      'Envoyée 20 ans dans le futur, elle a travaillé en attendant la rébellion.',
      'Son style repose sur la rapidité et un sabre particulièrement fin.',
      'Elle a perdu un membre en combattant un Empereur.',
      'Elle est connue pour sa beauté et sa grâce en combat.',
      "L'une des Neuf Fourreaux, femme transgenre de Wano.",
    ],
  },
  {
    name: 'Izo (Le Commandant en Kimono)',
    type: 'pirate',
    difficulty: 3,
    hints: [
      'Il a été danseur dans sa jeunesse avec sa sœur cadette.',
      'Il a quitté son pays pour suivre un seigneur sur un navire légendaire.',
      'Il est resté avec cet équipage quand le seigneur est parti avec un autre.',
      "Il est devenu commandant d'une division de cet équipage.",
      'Il utilise deux pistolets à silex comme armes principales.',
      'Il est revenu dans son pays pour aider une rébellion.',
      'Il est mort en affrontant des agents du pouvoir mondial.',
      'Ancien commandant de Barbe Blanche, frère de Kiku.',
    ],
  },
  {
    name: 'Scopper Gaban',
    type: 'pirate',
    difficulty: 3,
    hints: [
      "Troisième membre le plus important de l'équipage ayant trouvé le One Piece.",
      'Il utilisait deux haches comme armes principales.',
      'Avec le second, il formait un duo de bras droits.',
      "Il a participé au voyage vers l'île finale.",
      'Après la dissolution, son sort reste inconnu.',
      'Il était présent lors de la bataille contre un équipage légendaire.',
      "Son nom apparaît dans les souvenirs de l'ère du Roi.",
      'Membre des Roger Pirates, toujours en vie quelque part.',
    ],
  },
  {
    name: 'Shirahoshi (La Princesse Sirène)',
    type: 'civilian',
    difficulty: 2,
    hints: [
      "Elle a passé 10 ans enfermée par peur d'un prétendant obsessionnel.",
      'Elle pleure très facilement mais possède un pouvoir extraordinaire.',
      "Un futur Empereur l'a aidée à surmonter sa peur et à sortir.",
      'Un pirate la harcelait en lui lançant des armes depuis des années.',
      'Elle a participé à une réunion mondiale comme représentante.',
      'Son pouvoir est lié à des créatures marines géantes.',
      'Elle est la plus grande de son espèce jamais vue.',
      'Princesse et arme antique Poséidon.',
    ],
  },
  {
    name: 'Magellan (Le Directeur Vénéneux)',
    type: 'marine',
    difficulty: 2,
    hints: [
      'Il passe la majeure partie de sa journée aux toilettes à cause de son pouvoir.',
      "Son attaque ultime dissout tout ce qu'elle touche.",
      'Il a failli tuer un futur Empereur lors de leur affrontement.',
      'Il a vaincu à lui seul un autre futur Empereur et tout son équipage.',
      'Après une évasion massive, il a été rétrogradé.',
      'Son fruit lui permet de créer tous types de poisons.',
      'Il dirigeait la prison la plus sécurisée du monde.',
      "Ancien directeur d'Impel Down.",
    ],
  },
  {
    name: 'Hannyabal',
    type: 'marine',
    difficulty: 3,
    hints: [
      'Il rêvait ouvertement de prendre la place de son supérieur.',
      'Malgré sa lâcheté apparente, il a tenu tête à un futur Empereur.',
      'Son discours sur la protection des civils était sincère.',
      "Après un incident majeur, il a été promu au poste qu'il convoitait.",
      'Il porte un costume avec des cornes démoniaques.',
      'Sa détermination a impressionné même ses ennemis.',
      "Il a gagné son poste après l'évasion la plus célèbre de l'histoire.",
      "Actuel directeur d'Impel Down.",
    ],
  },
  {
    name: 'Shiki le Lion Doré',
    type: 'pirate',
    difficulty: 2,
    hints: [
      'Il commandait la plus grande flotte de son époque.',
      "Il faisait partie d'un équipage légendaire dans sa jeunesse.",
      "Il s'est enfoncé un gouvernail dans la tête lors d'un combat contre un rival.",
      'Il a attaqué seul le QG de la Marine après une exécution.',
      "Premier à s'être échappé d'une prison en se coupant les jambes.",
      'Il a disparu pendant 20 ans pour préparer sa revanche.',
      "Son fruit lui permet de faire flotter tout ce qu'il touche.",
      'Ancien membre des Rocks Pirates.',
    ],
  },

  // ==================== DIFFICULTÉ 4 ====================
  {
    name: 'Rob Lucci',
    type: 'civilian',
    difficulty: 4,
    hints: [
      "À 13 ans, il a massacré 500 soldats et les otages qu'ils retenaient.",
      'Il considère que la faiblesse est un péché méritant la mort.',
      'Il a passé 5 ans infiltré dans une entreprise pour une mission.',
      'Son partenaire est un pigeon portant une cravate.',
      'Il maîtrise six techniques secrètes au plus haut niveau.',
      "Il a livré le combat le plus difficile d'un futur Empereur à ce moment.",
      'Son fruit le transforme en félin tacheté.',
      "Assassin du Gouvernement, d'abord CP9 puis CP0.",
    ],
  },
  {
    name: 'Kaku',
    type: 'civilian',
    difficulty: 4,
    hints: [
      'Expert en estimation, il a évalué un navire comme irréparable.',
      'Son nez carré et allongé lui donne une silhouette reconnaissable.',
      'Il a mangé son fruit seulement après que sa couverture soit grillée.',
      'Sa transformation lui donne une apparence qui a été moquée.',
      'Il combine épée et pouvoirs animaux de façon unique.',
      'Il a affronté un épéiste dans un combat de lames intense.',
      'Après la défaite de son unité, il a rejoint une autre plus secrète.',
      'Ancien charpentier infiltré qui se transforme en girafe.',
    ],
  },
  {
    name: 'Spandam',
    type: 'civilian',
    difficulty: 4,
    hints: [
      "Son père était responsable de la condamnation d'un constructeur naval.",
      "Il est physiquement l'un des plus faibles de son organisation.",
      'Son épée a mangé un fruit et peut se transformer en pachyderme.',
      "Il a obtenu une autorisation d'attaque massive malgré les risques.",
      'Son obsession pour les promotions le rendait prêt à tout sacrifier.',
      'Il a humilié une prisonnière devant ses propres alliés.',
      'Après une défaite, il a subi la vengeance de ses subordonnés.',
      "Ancien chef d'une unité gouvernementale, responsable d'Enies Lobby.",
    ],
  },
  {
    name: 'Iceburg',
    type: 'civilian',
    difficulty: 4,
    hints: [
      "Apprenti d'un constructeur condamné à mort par le Gouvernement.",
      'Il a transformé une ville insulaire en centre mondial de son industrie.',
      'Il possède une souris de compagnie au nom de dinosaure.',
      "Il détenait des plans dangereux qu'il a confiés à un collègue devenu pirate.",
      "Il a survécu à une tentative d'assassinat qui l'a presque tué.",
      'Il rêve de transformer sa ville en navire navigable.',
      'Son rhume constant est une caractéristique récurrente.',
      'Maire de Water 7 et président de Galley-La.',
    ],
  },
  {
    name: 'Charlotte Perospero',
    type: 'pirate',
    difficulty: 4,
    hints: [
      "Premier-né d'une famille de 85 enfants, il a plus de 50 ans.",
      'Il a piégé un navire entier dans une substance solide sucrée.',
      "Il a perdu un bras dans l'explosion d'un guerrier qui se sacrifiait.",
      "Sa canne est une friandise qu'il lèche constamment.",
      'Il considère ses cadets avec un certain mépris.',
      'Sa prime dépasse les 700 millions.',
      'Son fruit crée et manipule des sucreries solides.',
      'Fils aîné de Big Mom, ministre des Bonbons.',
    ],
  },
  {
    name: 'Charlotte Oven',
    type: 'pirate',
    difficulty: 4,
    hints: [
      'Il est né triplet avec deux autres commandants importants.',
      'Il peut chauffer la mer elle-même pour empêcher les fuites.',
      "Il a tué un père qui tentait de sauver sa fille lors d'une fête.",
      'Sa stature imposante et son tempérament colérique le rendent redoutable.',
      "Il a poursuivi des ennemis jusqu'aux limites du territoire.",
      'Sa prime est de 300 millions.',
      'Son fruit génère une chaleur intense depuis son corps.',
      '4ème fils de Big Mom, ministre de la Cuisson.',
    ],
  },
  {
    name: 'Charlotte Daifuku',
    type: 'pirate',
    difficulty: 4,
    hints: [
      'Il est né triplet avec le plus fort des commandants de sa famille.',
      'En frottant son corps, il invoque une entité géante armée.',
      'Il a détruit plusieurs navires alliés par accident en combattant.',
      'Son tempérament impulsif le rend dangereux même pour les siens.',
      "Il a participé à la poursuite d'ennemis fuyant le territoire.",
      'Sa prime est de 300 millions.',
      'Son fruit invoque un génie bleu à la hallebarde.',
      '3ème fils de Big Mom.',
    ],
  },
  {
    name: "Who's Who",
    type: 'pirate',
    difficulty: 4,
    hints: [
      'Ancien agent gouvernemental, il a été emprisonné pour un échec.',
      "Sa mission ratée concernait la protection d'un fruit spécifique.",
      "Il s'est échappé et a rejoint un Empereur pour survivre.",
      'Il a une rancune contre un timonier pour des raisons personnelles.',
      'Il dirigeait une division de soldats masqués.',
      'Il connaît des secrets sur un esclave robotisé du pouvoir.',
      'Son fruit ancien le transforme en félin préhistorique.',
      'Membre des Tobiroppo, vaincu par Jinbe.',
    ],
  },
  {
    name: 'Black Maria',
    type: 'pirate',
    difficulty: 4,
    hints: [
      'Elle dirige un district de plaisirs dans une forteresse.',
      'Sa taille est gigantesque, dépassant les 8 mètres.',
      'Elle utilise des toiles piégées et un instrument comme armes.',
      'Elle a tendu un piège à un cuisinier en exploitant son code.',
      'Elle a combattu une archéologue et un squelette dans son repaire.',
      'Ses servantes sont des créatures créées par ses pouvoirs.',
      "Son fruit ancien lui donne une forme d'arachnide hybride.",
      'Membre des Tobiroppo de Kaido.',
    ],
  },
  {
    name: 'Ulti',
    type: 'pirate',
    difficulty: 4,
    hints: [
      "Elle a un tempérament explosif et s'énerve pour la moindre chose.",
      'Son frère cadet est son partenaire de combat permanent.',
      "Elle n'hésite pas à manquer de respect même à son Empereur.",
      'Ses coups de tête sont dévastateurs grâce à un crâne renforcé.',
      "Une autre Empereur l'a attaquée pour avoir menacé une enfant.",
      'Elle a survécu à plusieurs attaques mortelles.',
      'Son fruit ancien la transforme en dinosaure à tête dure.',
      'Membre des Tobiroppo, vaincue par Nami.',
    ],
  },
  {
    name: 'Page One',
    type: 'pirate',
    difficulty: 4,
    hints: [
      "Il est le frère cadet d'une membre colérique de son groupe.",
      "Plus calme qu'elle, il la tempère souvent.",
      'Il a été le premier de son groupe à affronter un certain cuisinier.',
      "Il a subi l'attaque d'une Empereur protégeant une petite fille.",
      'Sa transformation lui donne des griffes et une mâchoire redoutables.',
      'Il combat souvent en duo avec sa sœur.',
      'Son fruit ancien le transforme en dinosaure à voile dorsale.',
      'Membre des Tobiroppo de Kaido.',
    ],
  },
  {
    name: 'Sasaki',
    type: 'pirate',
    difficulty: 4,
    hints: [
      'Ancien capitaine, il a rejoint un Empereur après avoir été vaincu.',
      'Il a été trompé et attaché par un collègue de son groupe.',
      "Sa rancune contre ce traître l'a motivé pendant une bataille.",
      'Il commandait les soldats blindés de son équipage.',
      'Il peut utiliser la collerette de sa forme comme arme rotative.',
      'Sa transformation le rend particulièrement résistant.',
      'Son fruit ancien le transforme en dinosaure à cornes.',
      'Membre des Tobiroppo, vaincu par Franky.',
    ],
  },
  {
    name: 'Hyogoro (Hyogoro le Fleuri)',
    type: 'civilian',
    difficulty: 4,
    hints: [
      "Il était le plus respecté de sa profession avant l'arrivée d'un Empereur.",
      "Autrefois imposant, la captivité l'a réduit à un petit vieillard.",
      'Il a été condamné aux travaux forcés dans des mines.',
      'Il a enseigné une technique avancée au futur libérateur de son pays.',
      "Cette technique permet de projeter de la force à l'intérieur des cibles.",
      'Il a failli mourir transformé en monstre par un virus.',
      'Après la libération, il a repris sa place de leader.',
      'Boss yakuza de Wano, maître du Haki avancé.',
    ],
  },
  {
    name: 'Shinobu',
    type: 'civilian',
    difficulty: 4,
    hints: [
      'Elle était une kunoichi séduisante dans sa jeunesse.',
      'Elle a servi un seigneur légendaire il y a 20 ans.',
      "Elle n'a pas voyagé dans le temps avec les autres serviteurs.",
      "Elle s'est cachée pendant deux décennies en attendant.",
      'Son apparence actuelle contraste fortement avec sa beauté passée.',
      'Elle a utilisé son pouvoir pour faire grandir un enfant de 20 ans.',
      "Son fruit fait pourrir et vieillir ce qu'elle touche.",
      'Ninja qui a vieilli Momonosuke pour le combat.',
    ],
  },
  {
    name: 'Raizo (Raizo de la Brume)',
    type: 'civilian',
    difficulty: 4,
    hints: [
      'Un peuple entier a été torturé pendant des jours pour cacher sa présence.',
      'Malgré son apparence, il est considéré comme séduisant dans son pays.',
      'Sa tête est grosse et ses cheveux forment des parchemins.',
      'Ses techniques incluent des clones et des parchemins de stockage.',
      'Ces parchemins peuvent absorber et renvoyer des attaques.',
      "Il a voyagé 20 ans dans le futur avec d'autres serviteurs.",
      "Il a vaincu le chef ninja au service d'un tyran.",
      'Ninja des Neuf Fourreaux, protégé au prix de tortures.',
    ],
  },
  {
    name: 'Kurozumi Kanjuro',
    type: 'civilian',
    difficulty: 4,
    hints: [
      "Sa famille entière a été massacrée à cause d'un ancêtre criminel.",
      'Il a grandi en jouant un rôle sur scène pour survivre.',
      'Ses dessins prenaient vie mais étaient volontairement mauvais.',
      'Il a infiltré un groupe de serviteurs pendant des décennies.',
      "Sa vraie loyauté allait à un tyran qu'il servait en secret.",
      'Il a révélé sa trahison au pire moment, compromettant une rébellion.',
      'Son vrai talent de peintre crée des copies parfaites.',
      'Traître parmi les Neuf Fourreaux.',
    ],
  },
  {
    name: 'Bellamy la Hyène',
    type: 'pirate',
    difficulty: 4,
    hints: [
      'Il se moquait des rêveurs et de ceux qui croyaient aux légendes.',
      "Il a été humilié par quelqu'un qui a refusé de riposter.",
      "Après sa défaite, il a été abandonné par celui qu'il admirait.",
      'Il a participé à un tournoi pour regagner son honneur.',
      'Il a finalement gagné le respect de son ancien ennemi.',
      'Malgré sa rédemption, il a choisi de rester solitaire.',
      'Son fruit transforme ses membres en ressorts.',
      'Ancien admirateur de Doflamingo, battu deux fois par Luffy.',
    ],
  },
  {
    name: 'Pekoms',
    type: 'pirate',
    difficulty: 4,
    hints: [
      'Il a quitté son peuple pour devenir pirate malgré son apparence mignonne.',
      'Il peut utiliser une technique électrique propre à son espèce.',
      'Il a été touché par la gentillesse montrée à son peuple par des pirates.',
      'Il a trahi sa capitaine pour aider un équipage ami.',
      "Cette trahison lui a valu d'être gravement blessé.",
      'Sa forme animale lui donne une carapace défensive.',
      'Son fruit le transforme en tortue.',
      'Lion Mink, ancien combattant de Big Mom.',
    ],
  },
  {
    name: 'Tamago (Baron Tamago)',
    type: 'pirate',
    difficulty: 4,
    hints: [
      'Ses membres inférieurs sont démesurément longs à cause de son origine.',
      'Il parle en mélangeant des mots français dans ses phrases.',
      'Quand il est vaincu, il renaît sous une forme différente.',
      'Chaque renaissance le rend temporairement plus puissant.',
      'Il utilise une canne-épée avec une technique de jambes rapide.',
      'Il a négocié des accords entre son équipage et un autre peuple.',
      'Son fruit lui donne un cycle de régénération en plusieurs formes.',
      'Combattant de Big Mom de la tribu des Jambes Longues.',
    ],
  },
  {
    name: 'Kozuki Hiyori (Komurasaki)',
    type: 'civilian',
    difficulty: 4,
    hints: [
      'Enfant, elle a été séparée de son frère quand il a voyagé dans le temps.',
      'Elle a vécu cachée pendant 20 ans sans révéler son identité.',
      'Pour survivre, elle est devenue la plus célèbre de sa profession.',
      "Sous ce déguisement, elle volait l'argent des corrompus.",
      'Elle a feint sa mort pour échapper à un tyran qui la convoitait.',
      "Un samouraï infiltré l'a protégée en secret pendant des années.",
      'Elle joue du shamisen et connaît une chanson prophétique.',
      "Fille d'Oden, sœur du shogun actuel.",
    ],
  },

  // ==================== DIFFICULTÉ 5 ====================
  {
    name: 'Kuro (Kuro aux Mille Plans)',
    type: 'pirate',
    difficulty: 5,
    hints: [
      'Il a orchestré sa propre capture et exécution pour disparaître.',
      "Un hypnotiseur a pris sa place sur l'échafaud grâce à ses pouvoirs.",
      "Il a travaillé trois ans comme serviteur pour gagner la confiance d'une famille.",
      "Son plan était d'hériter la fortune d'une jeune fille malade.",
      "Ses griffes sur ses gants le rendent si rapide qu'il disparaît.",
      'Cette vitesse le rend dangereux même pour ses propres hommes.',
      'Il méprisait la vie de pirate et voulait une retraite paisible.',
      'Ancien capitaine vaincu par Luffy à Syrup.',
    ],
  },
  {
    name: "Don Krieg (L'Amiral Pirate)",
    type: 'pirate',
    difficulty: 5,
    hints: [
      'Il commandait une flotte de 50 navires et 5000 hommes à son apogée.',
      'Sa flotte a été décimée en seulement 7 jours dans une mer dangereuse.',
      'Un seul homme sur un petit radeau a détruit tous ses navires.',
      "Il portait une armure dorée couverte d'armes cachées.",
      'Son arsenal incluait des boulets, du poison et des bombes.',
      'Il a attaqué un restaurant flottant pour voler de la nourriture.',
      'Malgré sa puissance de feu, il a été vaincu par des poings nus.',
      "Chef de la plus grande flotte d'East Blue, écrasé par Mihawk.",
    ],
  },
  {
    name: "Gin (L'Homme-Démon)",
    type: 'pirate',
    difficulty: 5,
    hints: [
      "Affamé et mourant, quelqu'un lui a offert un repas gratuitement.",
      "Cette gentillesse l'a bouleversé car personne ne l'avait jamais aidé.",
      "Il était le commandant en second d'une grande flotte.",
      'Ses armes sont des tonfas avec des boulets aux extrémités.',
      "Il a reçu l'ordre d'utiliser un gaz mortel sur son bienfaiteur.",
      'Déchiré, il a défié son capitaine pour protéger celui-ci.',
      'Il a disparu après avoir été empoisonné par son propre camp.',
      'Second de Don Krieg, il a choisi la gratitude plutôt que la loyauté.',
    ],
  },
  {
    name: 'Wapol',
    type: 'civilian',
    difficulty: 5,
    hints: [
      "Fils d'un roi bienveillant, il a hérité d'un royaume hivernal.",
      'Il a fui quand des pirates ont attaqué au lieu de défendre son peuple.',
      "Il peut fusionner avec ce qu'il consomme, y compris des personnes.",
      'Après avoir été vaincu, il a créé un empire commercial de jouets.',
      "Le nouveau métal qu'il produit est très prisé dans le monde.",
      'Il a réussi à épouser une princesse et redevenir roi ailleurs.',
      "Son fruit lui permet de manger et transformer n'importe quoi.",
      'Ancien roi tyrannique de Drum.',
    ],
  },
  {
    name: 'Foxy (Le Renard Argenté)',
    type: 'pirate',
    difficulty: 5,
    hints: [
      'Son équipage a grandi en absorbant les perdants de ses propres jeux.',
      "Il pleure facilement quand on l'insulte mais rebondit aussitôt.",
      'Ses rayons ralentissent tout pendant 30 secondes.',
      "Il triche constamment dans les compétitions qu'il organise.",
      "Un futur Empereur l'a vaincu mais a récupéré tous ses membres perdus.",
      'Son rire distinctif est "Fehfehfeh".',
      'Son fruit tire des rayons qui ralentissent tout.',
      'Capitaine qui organise des Davy Back Fights.',
    ],
  },
  {
    name: 'Absalom',
    type: 'pirate',
    difficulty: 5,
    hints: [
      "Son corps a été modifié avec des parties d'animaux par un chirurgien.",
      'Il utilisait son pouvoir pour espionner les femmes dans leurs bains.',
      "Il a tenté de forcer une archéologue à l'épouser.",
      'Après la défaite de son capitaine, il est devenu journaliste.',
      'Il a été tué par un Empereur qui voulait voler son pouvoir.',
      "Ses modifications incluent la peau d'un éléphant.",
      'Son fruit le rend invisible et peut cacher des objets.',
      'Commandant de Thriller Bark, tué par Barbe Noire.',
    ],
  },
  {
    name: 'Hogback',
    type: 'civilian',
    difficulty: 5,
    hints: [
      'Il était un chirurgien de génie célébré dans le monde entier.',
      "Il a disparu après la mort d'une actrice dont il était obsédé.",
      'Il a rejoint un pirate pour pouvoir ramener cette femme à la vie.',
      'Ses créations sont des cadavres améliorés et recousus.',
      "L'actrice zombie le méprisait et cherchait à le tuer.",
      "Il s'est enfui quand son maître a été vaincu.",
      'Il créait des zombies en combinant corps et ombres.',
      'Médecin fou de Thriller Bark.',
    ],
  },
  {
    name: 'Morley (Le Pousseur)',
    type: 'revolutionary',
    difficulty: 5,
    hints: [
      'Il a créé un niveau secret dans une prison il y a un siècle.',
      'Il peut créer des tunnels, des murs ou des armes avec son pouvoir.',
      'Il porte des vêtements féminins malgré son apparence masculine.',
      "Il a participé au sauvetage d'un ancien roi transformé en arme.",
      "Il est d'une taille gigantesque comparé aux humains normaux.",
      "Son fruit repousse et modèle le sol comme de l'argile.",
      'Il est de la race des nouveaux géants.',
      "Commandant géant de l'Armée Révolutionnaire.",
    ],
  },
  {
    name: 'Lindbergh',
    type: 'revolutionary',
    difficulty: 5,
    hints: [
      "Il est l'inventeur et ingénieur de son organisation.",
      'Ses créations incluent des armes réfrigérantes et des jets packs.',
      'Il a créé un canon qui gèle instantanément ses cibles.',
      "Il porte des lunettes d'aviateur et un équipement de vol.",
      "Il dirige les forces d'une région de son organisation.",
      "Il a participé à une opération de sauvetage lors d'une réunion mondiale.",
      "C'est un chat de petite taille.",
      "Commandant Mink de l'Armée Révolutionnaire.",
    ],
  },
  {
    name: 'Belo Betty',
    type: 'revolutionary',
    difficulty: 5,
    hints: [
      'Elle porte une tenue révélatrice et un drapeau en permanence.',
      'Les personnes encouragées par elle voient leur force augmenter.',
      'Elle utilise ce pouvoir pour inciter les peuples à se rebeller.',
      "Elle a libéré un royaume avec l'aide des civils eux-mêmes.",
      'Elle commande une division régionale de son organisation.',
      "Elle a participé à une opération lors d'une réunion mondiale.",
      "Son fruit insuffle du courage aux gens autour d'elle.",
      "Commandante de l'Est de l'Armée Révolutionnaire.",
    ],
  },
  {
    name: 'Streusen (Le Chef)',
    type: 'pirate',
    difficulty: 5,
    hints: [
      'Il a découvert une petite fille seule après un incident traumatisant.',
      "Reconnaissant son potentiel, il l'a manipulée pour atteindre le pouvoir.",
      'Il a transformé un château entier en gâteau pour amortir une chute.',
      "Il est le chef cuisinier d'une Empereur depuis des décennies.",
      "Sa nourriture créée par son pouvoir n'a pas très bon goût.",
      'Malgré son âge avancé, il reste actif.',
      "Son fruit transforme n'importe quoi en nourriture.",
      "Fondateur de l'équipage de Big Mom.",
    ],
  },
  {
    name: 'Pound',
    type: 'civilian',
    difficulty: 5,
    hints: [
      "Il a été l'un des nombreux maris d'une Empereur redoutée.",
      'Comme tous les autres, il a été chassé après avoir rempli son rôle.',
      "Ses filles jumelles ne l'ont jamais connu.",
      'Il a passé des années à errer autour du territoire de son ex-femme.',
      'Il a tenté de protéger un équipage pour sauver une de ses filles.',
      "Un fils de Big Mom l'a apparemment décapité.",
      'Miraculeusement, il a survécu et retrouvé sa famille.',
      'Ex-mari de Big Mom, père de Chiffon et Lola.',
    ],
  },
  {
    name: 'Charlotte Brûlée',
    type: 'pirate',
    difficulty: 5,
    hints: [
      "Son visage porte de grandes cicatrices depuis une attaque dans l'enfance.",
      'Son frère aîné a juré de ne plus perdre après cette attaque sur elle.',
      'Elle peut créer un monde parallèle connectant tous les reflets.',
      "Elle peut aussi copier l'apparence des autres.",
      "Elle a capturé des intrus mais s'est fait retourner contre elle.",
      "Deux alliés l'ont utilisée pour se déplacer dans le territoire.",
      'Son fruit crée des miroirs et un monde parallèle.',
      '8ème fille de Big Mom.',
    ],
  },
  {
    name: "Charlotte Mont-d'Or",
    type: 'pirate',
    difficulty: 5,
    hints: [
      'Il ressemble à un personnage de livre avec un style victorien.',
      'Ses prisons de papier peuvent contenir des mondes entiers.',
      'Il gère les communications et la surveillance du territoire.',
      'Il coordonne son équipage comme un chef des opérations.',
      "Il a emprisonné une copie d'un allié dans un de ses livres.",
      'Sa bibliothèque contient de nombreux prisonniers et créatures.',
      'Son fruit piège les gens dans des livres.',
      '19ème fils de Big Mom.',
    ],
  },
  {
    name: 'Fukurokuju',
    type: 'civilian',
    difficulty: 5,
    hints: [
      'Sa tête allongée et ses longues oreilles le rendent unique.',
      "Il était le chef des forces ninja d'un pays isolé.",
      'Il a servi un tyran pendant 20 ans par opportunisme.',
      'Il a trahi son pays natal par calcul politique.',
      "Ses techniques incluent des fils d'oreille extensibles.",
      "Il a affronté un autre ninja dans un duel d'endurance interminable.",
      'Ce duel a duré des heures, aucun ne voulant abandonner.',
      'Chef des Oniwabanshu qui a servi Orochi.',
    ],
  },
  {
    name: 'Tama (O-Tama)',
    type: 'civilian',
    difficulty: 5,
    hints: [
      'Elle vit dans un village pauvre dévasté par la famine.',
      'Elle a survécu en mangeant du riz contaminé pendant des années.',
      'Un pirate lui avait promis de revenir la chercher quand il serait fort.',
      "Son pouvoir a retourné des centaines d'ennemis pendant un raid.",
      "Elle a attendu le retour de son ami sans savoir qu'il était mort.",
      "L'ami qu'elle attendait était Ace.",
      'Son fruit crée des dangos qui apprivoisent les animaux.',
      'Petite fille de Wano avec le pouvoir de dompter.',
    ],
  },
  {
    name: 'Yasuie (Shimotsuki Yasuie / Tonoyasu)',
    type: 'civilian',
    difficulty: 5,
    hints: [
      'Ancien puissant de son pays, il a tout perdu quand un tyran a pris le pouvoir.',
      'Il a vécu comme mendiant dans une ville pauvre.',
      "Les habitants l'aimaient car il partageait tout ce qu'il avait.",
      'Il a mangé un fruit défectueux le forçant à rire constamment.',
      "Il s'est sacrifié pour protéger le secret d'une rébellion.",
      'Avant son exécution, il a menti pour changer un plan de bataille.',
      'Sa fille ne pouvait que rire à sa mort à cause du même effet.',
      'Daimyo devenu mendiant, exécuté publiquement.',
    ],
  },
  {
    name: 'Tom (Le Constructeur)',
    type: 'civilian',
    difficulty: 5,
    hints: [
      "Il a construit le navire qui a atteint l'île finale du monde.",
      'Pour ce "crime", il a été traqué par le Gouvernement.',
      'Il a inventé un train révolutionnant le transport maritime.',
      'Cette invention devait lui valoir le pardon pour avoir aidé un pirate.',
      'Un agent a utilisé ses propres créations pour faire condamner des innocents.',
      'Il a été exécuté après avoir protégé ses apprentis.',
      'Ses deux apprentis sont devenus célèbres dans leur domaine.',
      "Constructeur naval légendaire qui a créé l'Oro Jackson.",
    ],
  },
  {
    name: 'Caribou',
    type: 'pirate',
    difficulty: 5,
    hints: [
      'Lui et son frère capturaient des Marines pour les enterrer.',
      'Il peut stocker des objets et des personnes dans son corps.',
      "Il a tenté d'infiltrer un équipage célèbre à plusieurs reprises.",
      "Il a découvert l'identité d'une arme antique par accident.",
      'Dans un pays isolé, il a aidé un futur Empereur en le nourrissant.',
      'Il cherche maintenant à vendre son information au plus offrant.',
      'Son fruit lui permet de devenir et créer de la boue.',
      'Pirate qui connaît le secret de Shirahoshi.',
    ],
  },
  {
    name: 'Rocks D. Xebec',
    type: 'pirate',
    difficulty: 5,
    hints: [
      "Son nom était effacé des livres d'histoire par le pouvoir mondial.",
      'Son équipage réunissait plusieurs futurs Empereurs sous ses ordres.',
      'Il voulait devenir le Roi du Monde, pas seulement des Pirates.',
      "Une alliance improbable entre un Marine et un pirate l'a vaincu.",
      'Cette bataille a eu lieu sur une île rayée des cartes.',
      'Sa défaite a propulsé un Marine au rang de Héros.',
      'Barbe Blanche, Kaido et Big Mom servaient sous lui.',
      'Capitaine des Rocks Pirates, détruit à God Valley.',
    ],
  },
];
