import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface CharacterSeed {
  name: string;
  type: 'player' | 'coach' | 'legend' | 'executive';
  difficulty: number;
  hints: string[];
}

const characters: CharacterSeed[] = [
  // ==================== LÉGENDES ====================
  {
    name: 'Michael Jordan',
    type: 'legend',
    difficulty: 1,
    hints: [
      "Né en 1963 à Brooklyn, quatrième d'une fratrie de cinq enfants. Sa famille a déménagé en Caroline du Nord quand il était petit.",
      "En seconde année de lycée, il n'a pas été retenu dans l'équipe varsity. Ce rejet l'a motivé pour le reste de sa carrière.",
      "À l'université, il a inscrit le panier décisif en finale NCAA lors de sa première année. Son coach était une légende qui lui faisait rarement confiance pour les gros tirs.",
      "Choisi en 3ème position en 1984. L'équipe qui avait le 2ème choix cherchait un pivot et l'a ignoré - une décision encore débattue aujourd'hui.",
      "Pendant des années, une équipe rivale de la Conférence Est l'a empêché d'atteindre les Finales grâce à une défense très physique.",
      "Il a remporté 6 titres sans jamais avoir besoin d'un match 7 en Finales. Son bilan sur la plus grande scène reste parfait.",
      'Il a quitté le basketball deux fois dans sa carrière - une fois pour jouer au baseball professionnellement.',
      'Sa marque de chaussures est devenue plus grande que la plupart des équipementiers sportifs. Son logo silhouette est reconnu mondialement.',
    ],
  },
  {
    name: 'Kobe Bryant',
    type: 'legend',
    difficulty: 1,
    hints: [
      'Né en 1978 à Philadelphie. Son père était basketteur professionnel et a emmené la famille en Europe pendant son enfance.',
      'Il a passé plusieurs années en Italie, devenant parfaitement bilingue. Cette expérience a forgé son éthique de travail légendaire.',
      'Il est entré dans la draft directement depuis le lycée en 1996. Sélectionné puis immédiatement transféré vers sa future franchise.',
      'Ses premières années ont été définies par son duo avec un pivot dominant. Ensemble, ils ont gagné trois titres consécutifs.',
      "En 2006, il a marqué 81 points en un seul match - le deuxième plus haut total de l'histoire de la ligue.",
      'Après le départ de son coéquipier star, il a gagné deux autres titres en tant que leader incontesté.',
      "Il s'est déchiré le tendon d'Achille à 34 ans mais est revenu jouer. Son dernier match : 60 points.",
      "Surnommé d'après un serpent venimeux, il représentait la compétitivité sans pitié. Décédé tragiquement en 2020.",
    ],
  },
  {
    name: 'Magic Johnson',
    type: 'legend',
    difficulty: 2,
    hints: [
      "Né en 1959 dans le Michigan, dans une ville industrielle connue pour l'automobile.",
      'Son surnom lui a été donné par un journaliste local après un match de lycée avec 36 points, 18 rebonds et 16 passes.',
      'Champion NCAA en deuxième année, battant en finale un joueur qui deviendrait son plus grand rival.',
      'Premier choix en 1979, il a joué pivot lors du match décisif des Finales de sa saison rookie et a dominé.',
      "À 2m06, il a révolutionné le poste de meneur par sa taille tout en dirigeant l'attaque.",
      "Sa rivalité avec un ailier de Boston a défini les années 80 et a sauvé la ligue d'une baisse de popularité.",
      'Il a pris sa retraite soudainement en 1991 après une annonce médicale choquante, mais est revenu plusieurs fois.',
      "Après sa carrière, il est devenu un homme d'affaires prospère et copropriétaire de plusieurs franchises sportives.",
    ],
  },
  {
    name: 'Larry Bird',
    type: 'legend',
    difficulty: 2,
    hints: [
      "Né en 1956 dans une petite ville de l'Indiana. Son enfance a été difficile - son père s'est suicidé quand il avait 18 ans.",
      "Il s'est d'abord inscrit dans une grande université mais est parti avant la saison, retournant dans son État natal.",
      "Drafté un an avant de jouer en NBA grâce à une faille dans les règles. L'équipe l'ayant choisi a attendu patiemment.",
      'Dès sa première saison, il a transformé une équipe de 29 victoires en équipe de 61 victoires.',
      "Sa rivalité avec un meneur flamboyant de l'Ouest a défini une époque et a propulsé la ligue vers de nouveaux sommets.",
      'Il a remporté trois titres de MVP consécutifs entre 1984 et 1986, rejoignant un club très exclusif.',
      'Des problèmes de dos chroniques ont raccourci sa carrière. Il jouait ses dernières saisons dans une douleur constante.',
      "Il est l'un des rares à avoir gagné MVP, MVP des Finales, Coach de l'Année et Dirigeant de l'Année.",
    ],
  },
  {
    name: 'Tim Duncan',
    type: 'legend',
    difficulty: 2,
    hints: [
      "Né en 1976 dans les Îles Vierges américaines. Il était d'abord nageur de compétition avant qu'un ouragan ne détruise les piscines locales.",
      "Il est resté quatre ans à l'université - rare pour un joueur de son calibre. Il a étudié la psychologie.",
      'Premier choix en 1997, sélectionné par une équipe qui avait stratégiquement mal joué pour améliorer ses chances à la loterie.',
      'Il a gagné des titres sur trois décennies différentes avec la même franchise - le seul joueur à avoir accompli cet exploit.',
      "Son style de jeu était fondamentalement solide mais sans fioritures. On le surnommait pour sa régularité et son manque d'éclat.",
      "Il a joué 19 saisons avec le même coach, formant l'un des duos les plus victorieux de l'histoire du sport.",
      "Considéré comme le meilleur ailier fort de tous les temps, bien qu'il ait souvent joué pivot dans les petites formations.",
      'Son attitude était si calme que montrer la moindre émotion devenait un événement. Il a été expulsé une fois pour avoir ri.',
    ],
  },
  {
    name: "Shaquille O'Neal",
    type: 'legend',
    difficulty: 1,
    hints: [
      "Né en 1972 sur une base militaire du New Jersey. Il déménageait souvent à cause de la carrière de son beau-père dans l'armée.",
      'À 13 ans, il mesurait déjà 1m98. Au lycée à San Antonio, il dominait tous ses adversaires.',
      'Il a dominé le basketball universitaire à LSU mais est parti après trois ans sans titre NCAA.',
      "Premier choix en 1992, il a eu un impact immédiat grâce à sa combinaison unique de taille et d'athlétisme.",
      "Il a remporté trois titres consécutifs avec un arrière talentueux, mais leur relation s'est détériorée.",
      "Après avoir quitté la Côte Ouest, il a gagné un quatrième titre à Miami aux côtés d'une future superstar.",
      'Ses lancers francs étaient notoirement mauvais, menant les équipes adverses à adopter une stratégie portant un nom spécifique.',
      'Reconverti en analyste TV, il est connu pour son humour et son autodérision constante.',
    ],
  },
  {
    name: 'Hakeem Olajuwon',
    type: 'legend',
    difficulty: 3,
    hints: [
      "Né en 1963 à Lagos, au Nigeria. Il n'a commencé à jouer au basketball qu'à l'âge de 15 ans.",
      'Il jouait gardien de but au football - un jeu de pieds qui définirait sa carrière de basketteur.',
      "À l'université, il a mené son équipe à trois Final Fours consécutifs et faisait partie d'une célèbre fraternité de grands joueurs de Houston.",
      'Choisi premier en 1984, un rang avant un joueur que beaucoup considèrent comme le meilleur de tous les temps.',
      "Il a gagné deux titres consécutifs pendant la première retraite de son rival, soulevant la question du 'et si'.",
      "Ses mouvements au poste bas étaient si raffinés qu'il organisait des camps d'été pour enseigner le jeu de pieds aux futures stars.",
      "Il a gagné le MVP, le titre de Défenseur de l'Année et le MVP des Finales la même saison - un exploit rare.",
      'Il est devenu citoyen américain et a représenté les États-Unis aux JO de 1996 après des années à jouer pour le Nigeria.',
    ],
  },
  {
    name: 'Kareem Abdul-Jabbar',
    type: 'legend',
    difficulty: 2,
    hints: [
      "Né en 1947 à New York sous un autre nom. Il s'est converti à l'islam et a changé de nom en 1971.",
      'Au lycée, il a mené son équipe à 71 victoires consécutives. Il était si dominant que le dunk a été interdit en NCAA à cause de lui.',
      'Il a remporté trois titres NCAA consécutifs avec UCLA, perdant seulement deux matchs en trois ans.',
      'Premier choix en 1969, il a immédiatement transformé une équipe perdante en prétendant au titre.',
      'Son tir signature était presque impossible à contrer - un tir en crochet exécuté avec un bras tendu.',
      'Il a remporté six titres de MVP en carrière, un record qui tient toujours.',
      'Transféré à Los Angeles, il a formé un duo légendaire avec un meneur flamboyant dans les années 80.',
      "Il a détenu le record du plus grand nombre de points en carrière pendant 39 ans jusqu'en 2023.",
    ],
  },
  {
    name: 'Wilt Chamberlain',
    type: 'legend',
    difficulty: 3,
    hints: [
      'Né en 1936 à Philadelphie, il mesurait déjà 1m88 à 10 ans et 2m16 au lycée.',
      "À l'université, les règles ont été modifiées spécifiquement pour limiter sa domination.",
      "En 1962, il a accompli un exploit qu'aucun autre joueur n'a égalé : marquer 100 points en un seul match.",
      "Cette même saison, il a maintenu une moyenne de plus de 50 points par match sur toute l'année.",
      "Malgré sa domination statistique, il n'a remporté que deux titres NBA, souvent battu par une équipe rivale de Boston.",
      "Il est le seul joueur de l'histoire à avoir mené la ligue aux passes décisives, prouvant sa polyvalence.",
      'Sa rivalité avec le pivot de Boston a défini une époque du basketball.',
      "Ses records semblent venir d'une autre ère - moyenne de 22.9 rebonds en carrière, 55 rebonds en un match.",
    ],
  },
  {
    name: 'Bill Russell',
    type: 'legend',
    difficulty: 3,
    hints: [
      'Né en 1934 en Louisiane, il a grandi dans la pauvreté et a fait face au racisme toute sa vie.',
      "À l'université de San Francisco, il a mené son équipe à deux titres NCAA consécutifs et 55 victoires d'affilée.",
      'Sélectionné en 1956, il a rejoint une franchise historique qui allait dominer la décennie.',
      'Il a remporté 11 titres NBA en 13 saisons - un record qui ne sera probablement jamais égalé.',
      'Sa rivalité avec un pivot dominant de Philadelphie a défini le basketball des années 60.',
      "Il est devenu le premier coach afro-américain de l'histoire des sports majeurs américains, s'entraînant lui-même en tant que joueur-coach.",
      'Cinq fois MVP, il privilégiait la défense et les rebonds aux statistiques individuelles offensives.',
      'Le trophée de MVP des Finales porte désormais son nom en hommage à sa grandeur.',
    ],
  },

  // ==================== JOUEURS ACTUELS ====================
  {
    name: 'LeBron James',
    type: 'player',
    difficulty: 1,
    hints: [
      "Né en 1984 dans l'Ohio. Élevé par une mère adolescente célibataire, ils déménageaient fréquemment.",
      'Dès le lycée, il faisait la couverture des magazines nationaux. Une chaîne sportive diffusait ses matchs.',
      'Premier choix en 2003, directement depuis le lycée. Il a signé des contrats publicitaires massifs avant ses débuts.',
      "Après sept saisons avec son équipe d'origine, il a annoncé son départ controversé lors d'une émission TV spéciale.",
      "Il est le seul joueur de l'histoire à avoir remporté des titres avec trois franchises différentes en tant que meilleur joueur.",
      'Il a dépassé le record historique de points en carrière en 2023, battant une marque que beaucoup pensaient intouchable.',
      'Il a disputé 10 Finales NBA, bien que son bilan dans celles-ci soit critiqué par ses détracteurs.',
      "En 2024, il a accompli quelque chose d'inédit : jouer un match NBA aux côtés de son fils.",
    ],
  },
  {
    name: 'Stephen Curry',
    type: 'player',
    difficulty: 1,
    hints: [
      "Né en 1988 dans le même hôpital qu'un autre futur MVP. Son père a joué 16 saisons en NBA.",
      "Malgré son pedigree, aucune grande université ne l'a vraiment recruté. Il est allé dans une petite fac de Caroline du Nord.",
      'Il a mené cette école au Elite Eight, devenant une sensation nationale grâce à son adresse au tir.',
      'Drafté 7ème en 2009, des blessures aux chevilles ont fait douter beaucoup de monde sur son avenir.',
      "En 2016, il est devenu le premier MVP unanime de l'histoire. Son équipe a établi le record de victoires en saison régulière.",
      'Il a fondamentalement changé la façon dont le basketball se joue - rendant le tir à trois points primordial.',
      "Il a battu le record historique de tirs à trois points en 2021, un record qu'on pensait imbattable.",
      'Sa célébration signature implique de regarder un objet imaginaire à son poignet après un gros tir.',
    ],
  },
  {
    name: 'Kevin Durant',
    type: 'player',
    difficulty: 1,
    hints: [
      'Né en 1988 à Washington D.C., il a grandi pour atteindre plus de 2m08 tout en gardant des compétences de meneur.',
      'Après une seule saison universitaire au Texas, il a remporté tous les trophées majeurs avant la draft.',
      "Choisi deuxième en 2007 derrière un joueur devenu un échec. Il s'est avéré être la vraie pépite de cette draft.",
      'Il a passé huit ans avec sa première franchise dans deux villes différentes, atteignant les Finales une fois.',
      "Sa décision de rejoindre une équipe qui venait de gagner 73 matchs a été qualifiée de plus lâche de l'histoire du sport.",
      'Il a remporté deux titres de MVP des Finales consécutifs avec cette équipe, faisant taire certains critiques.',
      "Il a demandé son transfert plusieurs fois, gagnant une réputation d'instabilité.",
      'Son utilisation des réseaux sociaux est notoire - il a été pris à utiliser des faux comptes pour se défendre.',
    ],
  },
  {
    name: 'Giannis Antetokounmpo',
    type: 'player',
    difficulty: 2,
    hints: [
      'Né en 1994 à Athènes de parents immigrés nigérians. Il vendait des objets dans la rue pour aider sa famille.',
      "Il n'a commencé le basketball qu'à 13 ans. Il était extrêmement brut quand les scouts l'ont découvert.",
      'Drafté 15ème en 2013, il était considéré comme un projet à long terme au potentiel incertain.',
      'Sa combinaison de taille, vitesse et compétences à 2m11 a créé un nouveau prototype de joueur.',
      'Il a remporté deux MVP consécutifs en 2019 et 2020, rejoignant un club très exclusif.',
      'En 2021, il a mené son équipe de petit marché au titre, mettant fin à une disette de 50 ans pour la franchise.',
      'Sa performance en Finales incluait un match à 50 points pour conclure la série, cimentant son statut parmi les grands.',
      "Son nom de famille est si long que les fans et médias n'utilisent souvent que son prénom.",
    ],
  },
  {
    name: 'Nikola Jokić',
    type: 'player',
    difficulty: 2,
    hints: [
      'Né en 1995 en Serbie. Il était en surpoids adolescent et plus intéressé par les chevaux que le basketball.',
      'Drafté 41ème en 2014, sa sélection a été annoncée pendant une publicité de fast-food.',
      'Sa capacité de passe au poste de pivot est sans précédent - il mène régulièrement son équipe aux passes décisives.',
      "Il a remporté trois MVP consécutifs de 2021 à 2024, rejoignant seulement deux autres joueurs dans l'histoire.",
      "Il a mené son équipe à son premier titre en 2023, remportant le MVP des Finales tout en ayant l'air presque ennuyé.",
      'Son style de jeu est décrit comme anti-athlétique - lent, méthodique, mais incroyablement efficace.',
      "Il a déclaré qu'il préférerait être chez lui avec ses chevaux plutôt qu'au All-Star Weekend.",
      'Son surnom est un jeu de mots sur son nom, faisant référence à un célèbre méchant de comics.',
    ],
  },
  {
    name: 'Luka Dončić',
    type: 'player',
    difficulty: 2,
    hints: [
      'Né en 2001 à Ljubljana, en Slovénie. Il a signé avec un club professionnel à 13 ans.',
      "Il a remporté le MVP de l'EuroLeague à 18 ans, dominant des adultes avant même d'arriver en NBA.",
      "Drafté 3ème en 2018, beaucoup ont critiqué les équipes qui l'ont laissé passer.",
      "Son step-back à trois points est devenu l'un des mouvements les plus imparables du jeu.",
      'Il a été sélectionné plusieurs fois dans la première équipe All-NBA avant ses 25 ans - une compagnie historiquement élite.',
      'Ses plaintes auprès des arbitres sont constantes, lui valant un nombre alarmant de fautes techniques.',
      "En 2024, il a mené son équipe en Finales pour la première fois depuis l'ère du championnat de la franchise.",
      'Son style a été comparé à une version gauchère de certaines légendes pour sa ruse et son intelligence.',
    ],
  },
  {
    name: 'Joel Embiid',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 1994 au Cameroun. Il n'a pas joué au basketball avant 15 ans, préférant le football et le volleyball.",
      'Une seule saison universitaire avant que des blessures ne compromettent sa position à la draft - il a quand même été choisi 3ème.',
      "Il a raté ses deux premières saisons NBA à cause de blessures aux pieds. Beaucoup se demandaient s'il jouerait un jour.",
      'Quand il est en bonne santé, il est sans doute le pivot le plus dominant offensivement depuis le début des années 2000.',
      'Il a remporté le MVP 2023, devenant le premier joueur de son pays à gagner ce trophée.',
      'Son trolling sur les réseaux sociaux est légendaire - il provoque régulièrement adversaires et même coéquipiers.',
      'Ses performances en playoffs ont été critiquées comme irrégulières, souvent à cause de blessures.',
      "Il a choisi de représenter les États-Unis internationalement bien qu'il soit éligible pour d'autres pays.",
    ],
  },
  {
    name: 'Jayson Tatum',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 1998 à Saint-Louis. Sa mère était adolescente quand il est né, un fait qu'il a partagé publiquement.",
      "Il a joué une saison à Duke sous un coach légendaire avant d'entrer dans la draft.",
      'Drafté 3ème en 2017, il a immédiatement montré un potentiel de star à seulement 19 ans.',
      "Il a été sélectionné plusieurs fois All-NBA et est considéré comme le meilleur joueur d'une franchise historique.",
      'Il a une célébration signature où il pointe deux doigts, en référence au prénom de son fils.',
      'Son équipe a finalement percé en 2024, mettant fin à une disette de 18 ans sans titre pour la franchise.',
      "Ses critiques l'ont qualifié d'irrégulier dans les grands moments, malgré plusieurs parcours profonds en playoffs.",
      'Il porte le numéro 0, représentant selon lui le nombre de personnes qui ne croyaient pas en lui.',
    ],
  },
  {
    name: 'Anthony Edwards',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 2001 à Atlanta. Il a perdu sa mère et sa grand-mère d'un cancer avant sa dernière année de lycée.",
      "Une seule saison universitaire en Géorgie, bien que l'équipe ait raté le tournoi NCAA.",
      "Premier choix en 2020, sélectionné par une franchise qui n'avait pas fait les playoffs depuis plus de 15 ans.",
      'Son athlétisme et son charisme ont immédiatement suscité des comparaisons avec des légendes du passé.',
      "Il a ouvertement déclaré préférer le football américain au basketball, disant jouer au basket pour l'argent.",
      "Sa confiance frôle l'arrogance - il a garanti des victoires et provoqué des adversaires publiquement.",
      'À 23 ans, il était déjà considéré parmi les 10 meilleurs joueurs de la ligue par la plupart des analystes.',
      "Son surnom fait référence à un personnage fictif d'un film comique des années 80 sur un animal de compagnie.",
    ],
  },
  {
    name: 'Victor Wembanyama',
    type: 'player',
    difficulty: 2,
    hints: [
      'Né en 2004 en France. À 15 ans, il mesurait déjà 2m13 et était appelé prospect générationnel.',
      'Avant la draft, les scouts le comparaient au meilleur prospect depuis un certain premier choix de 2003.',
      "Premier choix en 2023, sélectionné par l'équipe avec le pire bilan de la ligue.",
      'Son envergure de 2m44 lui permet de contester des tirs tout en restant à plat près du cercle.',
      'Il peut dribbler comme un meneur, tirer à trois points et contrer des tirs à un niveau élite - une combinaison unique.',
      "Sa saison rookie a inclus plusieurs matchs avec 5+ contres, quelque chose d'extrêmement rare pour n'importe quel joueur.",
      'On le compare à une créature mythologique car sa combinaison de taille et compétences semble impossible.',
      'Il joue pour une franchise connue pour développer des grands internationaux en joueurs légendaires.',
    ],
  },
  {
    name: 'Kawhi Leonard',
    type: 'player',
    difficulty: 2,
    hints: [
      'Né en 1991 à Los Angeles. Son père a été assassiné dans un car wash quand il avait 16 ans.',
      'Drafté 15ème en 2011, il a été immédiatement transféré contre un joueur considéré comme plus prêt pour la NBA.',
      "Il s'est développé en joueur d'élite des deux côtés du terrain sous un coach légendaire connu pour le développement des joueurs.",
      'MVP des Finales en 2014, il a muselé le meilleur joueur du monde dans cette série.',
      'Après une blessure mystérieuse et un conflit avec son équipe, il a forcé un transfert vers une équipe canadienne en 2018.',
      "Il a remporté son deuxième titre et MVP des Finales en 2019, inscrivant un des tirs les plus iconiques de l'histoire des playoffs.",
      "Son expression émotionnelle est quasi inexistante, menant à des blagues sur le fait qu'il serait un robot.",
      'Ses mains sont devenues un mème - capables de tenir un ballon de basket comme une balle de tennis.',
    ],
  },
  {
    name: 'James Harden',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 1989 à Los Angeles. Il a joué au basketball universitaire en Arizona avant d'entrer dans la draft.",
      'Drafté 3ème en 2009, il a commencé sa carrière comme sixième homme dans une jeune équipe talentueuse.',
      "Après un désaccord contractuel, il a été transféré et est devenu le point focal de l'attaque de sa nouvelle équipe.",
      "MVP en 2018 après avoir maintenu une moyenne de plus de 30 points par match avec son style basé sur l'isolation.",
      "Son step-back à trois points est considéré comme l'un des mouvements les plus imparables de l'histoire.",
      'Ses critiques pointent ses déceptions en playoffs, notamment des effondrements notables en matchs éliminatoires.',
      'Il a été transféré plusieurs fois après que ses relations avec les organisations se sont détériorées.',
      "Sa barbe est sa marque de fabrique - il a dit ne pas l'avoir rasée depuis plus de dix ans.",
    ],
  },
  {
    name: 'Russell Westbrook',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 1988 à Long Beach, Californie. Il n'était pas très recruté jusqu'à une poussée de croissance tardive.",
      'Il a joué à UCLA, devenant un prospect NBA après avoir été initialement sous-estimé.',
      'Drafté 4ème en 2008, il a formé un duo explosif avec un autre futur MVP.',
      'Après le départ de son coéquipier star, il a gagné le MVP en 2017 en affichant un triple-double de moyenne sur toute la saison.',
      "Il a affiché un triple-double de moyenne sur quatre saisons différentes - quelque chose qu'on pensait impossible.",
      "Il détient le record de triple-doubles en carrière, dépassant une légende qu'on pensait intouchable.",
      'Son style de jeu est agressif sans relâche, menant à des actions spectaculaires comme à des pertes de balle coûteuses.',
      "Il a été transféré et a changé d'équipe plusieurs fois, peinant à trouver le bon fit en fin de carrière.",
    ],
  },
  {
    name: 'Chris Paul',
    type: 'player',
    difficulty: 2,
    hints: [
      'Né en 1985 en Caroline du Nord. Son grand-père a été assassiné le lendemain de son engagement universitaire.',
      'Il a marqué 61 points lors de son match de lycée suivant - un point pour chaque année de vie de son grand-père.',
      "Drafté 4ème en 2005, il est immédiatement devenu l'un des meilleurs meneurs de la ligue.",
      "Il a été finaliste au MVP plusieurs fois mais n'a jamais atteint les Finales NBA, une critique constante.",
      'Il a été transféré vers plusieurs équipes, souvent après que ses contrats sont devenus des fardeaux financiers.',
      'Son QI basket est considéré parmi les plus élevés de tous les temps, mais ses échecs en playoffs définissent les débats à son sujet.',
      'Il a dirigé le syndicat des joueurs à travers plusieurs négociations collectives, connu pour son sens des affaires.',
      'Son surnom reflète sa position et sa capacité à contrôler les matchs comme un général sur le terrain.',
    ],
  },
  {
    name: 'Damian Lillard',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 1990 à Oakland, Californie. Il est allé dans une petite université de l'Utah, pas une puissance du basketball.",
      "Drafté 6ème en 2012, il a remporté le titre de Rookie de l'Année et est immédiatement devenu une pierre angulaire.",
      'Il a inscrit plusieurs tirs décisifs de série, dont un célèbre trois points à plus de 11 mètres pour gagner une série de playoffs.',
      'Il est resté 11 ans loyal à une franchise de petit marché, devenant leur meilleur joueur de tous les temps.',
      'En 2023, il a demandé un transfert vers une destination spécifique mais a été envoyé ailleurs.',
      'Ses performances clutch lui ont valu un surnom lié au temps et aux moments décisifs.',
      'Il est aussi rappeur avec une vraie carrière musicale sous un nom de scène.',
      "Il fait un signe d'au revoir aux adversaires après avoir inscrit des tirs en fin de match, une célébration signature.",
    ],
  },
  {
    name: 'Kyrie Irving',
    type: 'player',
    difficulty: 2,
    hints: [
      'Né en 1992 en Australie pendant que son père jouait professionnellement là-bas. Il a déménagé aux États-Unis tout petit.',
      "Il n'a joué que 11 matchs universitaires à cause d'une blessure avant d'être drafté premier en 2011.",
      'Son dribble est considéré comme le meilleur de tous les temps - il peut finir près du cercle de manières impossibles.',
      "Il a inscrit l'un des tirs les plus célèbres de l'histoire des Finales, un trois points dans le Game 7 de 2016.",
      "Après avoir gagné ce titre, il a demandé un transfert, voulant être 'le patron' de sa propre équipe.",
      'Ses controverses hors terrain incluent la promotion de théories conspirationnistes et des absences pour raisons personnelles.',
      'Il a joué pour plusieurs équipes, partant souvent dans le drame et les conflits avec les organisations.',
      'Il a récemment rejoint une autre superstar au Texas, espérant une autre campagne de championnat.',
    ],
  },
  {
    name: 'Draymond Green',
    type: 'player',
    difficulty: 3,
    hints: [
      "Né en 1990 au Michigan. Il a joué quatre ans à l'université, ne partant pas plus tôt malgré sa productivité.",
      "Drafté 35ème en 2012 - le dernier choix du deuxième tour. Presque personne ne s'attendait à ce qu'il devienne une star.",
      "Il s'est développé en l'un des meilleurs défenseurs de tous les temps malgré un gabarit insuffisant pour son poste.",
      "Défenseur de l'Année en 2017, il a été sélectionné plusieurs fois dans les équipes All-Defensive.",
      "Son QI basket et sa capacité de création en tant qu'intérieur ont révolutionné ce que les équipes recherchent chez les ailiers forts.",
      'Il a gagné quatre titres mais est souvent critiqué pour ses explosions émotionnelles et ses fautes techniques.',
      'Il a été suspendu pendant les Finales 2016 après avoir accumulé des points de fautes flagrantes, coûtant potentiellement le titre à son équipe.',
      'Il est récemment devenu une personnalité médiatique avec son propre podcast, connu pour ses prises de position controversées.',
    ],
  },
  {
    name: 'Jimmy Butler',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 1989 au Texas. Il était sans-abri adolescent après que sa mère l'a mis dehors.",
      "Peu recruté, il est passé par une junior college avant d'être transféré à Marquette.",
      'Drafté 30ème en 2011, il était un choix de fin de premier tour qui a dépassé toutes les attentes.',
      "Il est connu pour son éthique de travail intense, battant régulièrement ses coéquipiers à l'entraînement.",
      'Il a forcé sa sortie de deux franchises via des demandes de transfert après des conflits avec les organisations.',
      'Il a mené une équipe outsider aux Finales en 2020, manquant de peu de battre les favoris dans une performance légendaire.',
      "Sa personnalité est intense - il s'est heurté à des coachs et des stars tout au long de sa carrière.",
      "Il a transformé son image plusieurs fois, incluant une entreprise de café qu'il promeut constamment.",
    ],
  },
  {
    name: 'Paul George',
    type: 'player',
    difficulty: 2,
    hints: [
      'Né en 1990 en Californie. Il a joué au basketball universitaire à Fresno State, pas une puissance traditionnelle.',
      "Drafté 10ème en 2010, il s'est développé en joueur calibre All-Star en quelques années.",
      "Il a subi une horrible blessure à la jambe lors d'un entraînement avec Team USA en 2014, mettant presque fin à sa carrière.",
      'Il est revenu pour être sélectionné plusieurs fois All-Star et All-NBA, prouvant sa résilience.',
      'Sa performance dans une série de playoffs contre Toronto lui a valu un surnom devenu un mème.',
      "Il a demandé un transfert d'Indiana, puis un autre d'Oklahoma City, cherchant des opportunités de titre.",
      "Sa capacité au tir à trois points combinée à sa défense en fait l'un des meilleurs two-way players.",
      "Il a signé avec une nouvelle équipe en 2024, retrouvant un ancien coéquipier d'un échec en playoffs de 2020.",
    ],
  },
  {
    name: 'Devin Booker',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 1996, fils d'un ancien joueur NBA. Il a grandi autour du basketball professionnel.",
      "Il a joué une saison à Kentucky sous un coach célèbre, mais n'était pas la star principale de l'équipe.",
      'Drafté 13ème en 2015, il est tombé plus bas que prévu et a rapidement prouvé que les équipes avaient eu tort.',
      'En 2017, à seulement 20 ans, il a marqué 70 points en un match - le plus jeune joueur à atteindre ce total.',
      'Pendant des années, il était une star sur une équipe perdante, menant à des questions sur son impact sur la victoire.',
      'En 2021, il a mené son équipe aux Finales NBA pour la première fois depuis 1993.',
      'Son jeu au milieu de terrain est exceptionnel, avec un arsenal complet de tirs et de mouvements.',
      'Il est connu pour sa relation très médiatisée avec une célébrité, faisant de lui un habitué des tabloïds.',
    ],
  },
  {
    name: 'Ja Morant',
    type: 'player',
    difficulty: 2,
    hints: [
      'Né en 2001 en Caroline du Sud. Il est allé dans une petite université que personne ne connaissait.',
      'Il a explosé lors du tournoi NCAA, menant son école à une victoire surprise au premier tour.',
      'Drafté 2ème en 2019, juste derrière un joueur très hyped qui a lutté avec les blessures.',
      "Son athlétisme et sa capacité à finir au cercle sont parmi les plus spectaculaires de l'histoire de la ligue.",
      'Il a été nommé Most Improved Player et sélectionné All-Star, devenant le visage de sa franchise.',
      'Des controverses hors terrain ont terni son image, incluant des incidents impliquant des armes sur les réseaux sociaux.',
      "Il a été suspendu pendant une partie significative d'une saison à cause de ces incidents.",
      'Son style de jeu téméraire lui vaut des comparaisons avec des légendes, mais aussi des inquiétudes sur sa durabilité.',
    ],
  },
  {
    name: 'Zion Williamson',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 2000 en Caroline du Sud. Au lycée, ses dunks viraux l'ont rendu célèbre avant même l'université.",
      'À Duke, il a été le joueur universitaire le plus hyped depuis des années. Une chaussure a explosé pendant un match.',
      "Premier choix en 2019, il était comparé à des légendes pour sa combinaison unique de puissance et d'athlétisme.",
      'Ses premières années ont été marquées par des blessures constantes, le limitant à peu de matchs.',
      'Quand il joue, sa domination près du cercle est presque impossible à arrêter.',
      'Son poids a été un sujet constant de discussion, affectant sa disponibilité et son jeu.',
      'Sa franchise a eu du mal à construire autour de lui à cause de ses absences répétées.',
      "Malgré les inquiétudes, quand il est en bonne santé, il affiche des statistiques dignes d'un All-Star.",
    ],
  },
  {
    name: 'Trae Young',
    type: 'player',
    difficulty: 2,
    hints: [
      "Né en 1998 au Texas. À l'université d'Oklahoma, il a explosé en tant que freshman avec des stats incroyables.",
      "Sa capacité à tirer de très loin, parfois du logo, l'a fait comparer à une certaine légende du tir.",
      'Drafté 5ème en 2018, il a été immédiatement échangé contre un autre prospect prometteur.',
      "En 2021, il a mené son équipe jusqu'aux Finales de Conférence Est, battant la franchise de New York au passage.",
      'Ses gestes de provocation envers le public de New York sont devenus légendaires.',
      'Son jeu de pick-and-roll est parmi les plus efficaces de la ligue.',
      'Critiqué pour sa défense et son style de jeu qui attire beaucoup de fautes.',
      'Ses cheveux et son apparence sont souvent sujet de moqueries sur les réseaux sociaux.',
    ],
  },

  // ==================== COACHES ====================
  {
    name: 'Gregg Popovich',
    type: 'coach',
    difficulty: 2,
    hints: [
      "Né en 1949 dans l'Indiana. Il a fait l'Académie de l'Air Force et a servi dans l'armée avant de coacher.",
      "Il est devenu GM de son équipe actuelle en 1994, puis a pris la décision controversée de virer le coach et de s'embaucher lui-même.",
      'Il a drafté un natif des Îles Vierges en 1997, commençant un partenariat qui allait durer 19 ans.',
      'Ses équipes ont remporté cinq titres sur trois décennies, toutes avec la même organisation.',
      'Il est célèbre pour ses réponses hilairement courtes et sarcastiques en interviews.',
      "Sa philosophie de coaching met l'accent sur le mouvement de balle, la défense et le basketball fondamental.",
      "Il est devenu le coach le plus victorieux de l'histoire de la NBA en 2022, dépassant un record établi depuis des années.",
      'Maintenant dans sa fin de septantaine, il développe le prospect le plus hyped depuis 2003.',
    ],
  },
  {
    name: 'Steve Kerr',
    type: 'coach',
    difficulty: 2,
    hints: [
      'Né en 1965 à Beyrouth, au Liban. Son père, professeur, a été assassiné par des terroristes quand il avait 18 ans.',
      "En tant que joueur, c'était un shooteur d'élite qui a remporté cinq titres avec deux franchises différentes.",
      "Il a inscrit l'un des tirs les plus célèbres de l'histoire des Finales quand son coéquipier lui a passé la balle pour le game-winner.",
      'Après des années comme analyste TV et dirigeant, il a pris son premier poste de coach en 2014.',
      'Lors de sa première saison comme coach, son équipe a remporté le titre avec un style de jeu révolutionnaire.',
      'Ses équipes ont gagné quatre championnats et disputé six Finales en neuf ans.',
      "Il est connu pour son activisme politique, s'exprimant sur des sujets de société plus que la plupart des coachs.",
      "Il travaille avec le meilleur shooteur de l'histoire depuis plus d'une décennie.",
    ],
  },
  {
    name: 'Phil Jackson',
    type: 'legend',
    difficulty: 2,
    hints: [
      'Né en 1945 au Montana de parents pasteurs pentecôtistes. Son éducation était très stricte et religieuse.',
      'En tant que joueur, il a remporté deux titres avec les Knicks comme remplaçant dans les années 70.',
      'Il est devenu connu pour incorporer le bouddhisme zen et la philosophie amérindienne dans son coaching.',
      'Il a remporté six titres en coachant un arrière que beaucoup considèrent comme le meilleur joueur de tous les temps.',
      'Il a ensuite gagné cinq autres titres en coachant un autre arrière souvent comparé à ce joueur.',
      "Son système d'attaque en triangle était controversé mais indéniablement efficace avec du talent d'élite.",
      'Il détient le record du plus grand nombre de titres en tant que coach avec 11, devant des prédécesseurs légendaires.',
      'Sa tentative ultérieure en tant que dirigeant a été bien moins réussie, marquée par de mauvaises décisions et du drama.',
    ],
  },
  {
    name: 'Pat Riley',
    type: 'executive',
    difficulty: 3,
    hints: [
      'Né en 1945 à Rome, New York. Il a joué neuf saisons NBA, remportant un titre comme remplaçant.',
      "En tant que coach, il a créé le basketball 'Showtime' dans les années 80 avec un style rapide et divertissant.",
      'Il a remporté quatre titres en coachant une équipe avec un meneur légendaire et un pivot.',
      "Il a déposé la marque 'three-peat' après que son équipe a gagné deux titres consécutifs mais échoué au troisième.",
      "Il est l'un des trois seuls à avoir gagné des titres en tant que joueur, coach et dirigeant.",
      'En 2006, il est sorti de sa retraite de coach pour mener son équipe à un improbable comeback en Finales.',
      'Il a recruté une superstar en 2010 avec un pitch légendaire, construisant une équipe qui a gagné deux titres.',
      'Son organisation est célèbre pour sa culture exigeante, requérant des standards de condition physique pour tous les joueurs.',
    ],
  },
  {
    name: 'Erik Spoelstra',
    type: 'coach',
    difficulty: 3,
    hints: [
      "Né en 1970 dans l'Illinois. Son père était un dirigeant NBA, lui donnant une exposition précoce à la ligue.",
      "Il a commencé sa carrière comme coordinateur vidéo, gravissant les échelons pendant plus d'une décennie.",
      "Il est devenu coach principal en 2008, héritant d'une équipe menée par un arrière star vieillissant.",
      "Quand trois superstars ont uni leurs forces en 2010, beaucoup s'attendaient à ce qu'il soit remplacé. Il ne l'a pas été.",
      'Il a mené cette super équipe à quatre Finales consécutives et deux titres.',
      "Après le départ de ces stars, il a reconstruit avec des choix de draft et des joueurs que d'autres avaient abandonnés.",
      'Ses schémas défensifs sont considérés parmi les meilleurs de la ligue, innovant avec des concepts de zone.',
      "Il est l'un des coachs avec la plus longue ancienneté dans la ligue, restant avec une seule franchise toute sa carrière.",
    ],
  },
  {
    name: 'Doc Rivers',
    type: 'coach',
    difficulty: 3,
    hints: [
      'Né en 1961 à Chicago. En tant que joueur, il était un meneur solide qui a joué 13 saisons NBA.',
      "Son surnom lui a été donné par un coéquipier qui pensait qu'il ressemblait à un personnage de dessin animé.",
      'Il a commencé sa carrière de coach à Orlando, menant une jeune équipe aux Finales de Conférence.',
      'Il a remporté un titre en 2008 en coachant un trio de futures légendes réunies à Boston.',
      'Ce titre a mis fin à une disette de 22 ans pour la franchise.',
      'Il est connu pour ses capacités de communicateur et de motivateur, mais critiqué pour ses ajustements tactiques.',
      'Ses équipes ont subi plusieurs effondrements en playoffs après avoir mené 3-1 dans une série.',
      'Il a coaché plusieurs franchises emblématiques incluant Boston, les Clippers et Philadelphie.',
    ],
  },

  // ==================== LÉGENDES SUPPLÉMENTAIRES ====================
  {
    name: 'Charles Barkley',
    type: 'legend',
    difficulty: 2,
    hints: [
      "Né en 1963 en Alabama. À l'université d'Auburn, il était surnommé 'The Round Mound of Rebound' pour son gabarit.",
      'Drafté 5ème en 1984, il était considéré trop petit et trop lourd pour être un ailier fort dominant.',
      "Il a prouvé que ses détracteurs avaient tort, devenant l'un des ailiers forts les plus dominants de son époque.",
      'MVP en 1993, il a mené son équipe aux Finales cette année-là, perdant contre une dynastie.',
      "Malgré une carrière brillante, il n'a jamais remporté de titre NBA - quelque chose qu'il évoque souvent avec humour.",
      'Il était connu pour son jeu physique et sa personnalité sans filtre.',
      "Après sa retraite, il est devenu l'un des analystes TV les plus populaires et divertissants.",
      'Ses débats avec un ancien rival sur le plateau sont devenus légendaires.',
    ],
  },
  {
    name: 'Scottie Pippen',
    type: 'legend',
    difficulty: 2,
    hints: [
      'Né en 1965 en Arkansas, le plus jeune de 12 enfants. Il a joué dans une petite université peu connue.',
      "Drafté 5ème en 1987, il a été immédiatement échangé vers une équipe qui construisait autour d'une future légende.",
      "Il est devenu l'un des meilleurs défenseurs de l'histoire, capable de garder toutes les positions.",
      'Il a remporté six titres aux côtés de son coéquipier superstar dans les années 90.',
      "Beaucoup le considèrent comme le meilleur 'Robin' de l'histoire - l'acolyte parfait d'une légende.",
      "Il a eu des tensions avec son organisation concernant son contrat, qu'il estimait sous-évalué.",
      "Quand sa superstar coéquipière est partie jouer au baseball, il a montré qu'il pouvait mener une équipe seul.",
      'Après sa retraite, il a été critique de son ancien partenaire, créant une controverse.',
    ],
  },
  {
    name: 'Dennis Rodman',
    type: 'legend',
    difficulty: 2,
    hints: [
      "Né en 1961 au New Jersey. Il n'a pas joué au basketball au lycée et a travaillé comme concierge avant de se faire remarquer.",
      "Drafté 27ème en 1986, il n'était pas considéré comme un futur impact player.",
      'Il est devenu le meilleur rebondeur de son époque, menant la ligue au rebond sept saisons consécutives.',
      "Il a remporté deux titres avec Detroit dans le cadre des 'Bad Boys', puis trois autres avec Chicago.",
      'Son look excentrique - cheveux colorés, piercings, tatouages - a fait de lui une icône culturelle.',
      'Il a eu une relation très médiatisée avec une célébrité de la pop culture.',
      'Sa défense sur les meilleurs joueurs adverses était légendaire, spécialement en Finales.',
      'Ses problèmes personnels et son comportement erratique ont souvent fait les gros titres.',
    ],
  },
  {
    name: 'Allen Iverson',
    type: 'legend',
    difficulty: 2,
    hints: [
      'Né en 1975 en Virginie. Il excellait aussi au football américain et aurait pu jouer en NFL.',
      'À Georgetown, il est devenu une star universitaire sous un coach légendaire.',
      'Premier choix en 1996, il a immédiatement apporté un style de jeu jamais vu auparavant en NBA.',
      'MVP en 2001, il a mené son équipe aux Finales presque à lui seul, volant un match à une dynastie.',
      "Son crossover est devenu l'un des mouvements les plus emblématiques de l'histoire du basketball.",
      "Sa conférence de presse sur 'l'entraînement' est devenue un moment iconique de la culture pop.",
      'Il a changé la culture de la NBA - style vestimentaire, tattoos, attitude - pour toute une génération.',
      'Malgré sa petite taille (1m83), il jouait sans peur contre des joueurs beaucoup plus grands.',
    ],
  },
  {
    name: 'Dirk Nowitzki',
    type: 'legend',
    difficulty: 2,
    hints: [
      'Né en 1978 en Allemagne. Il jouait au handball et au tennis avant de se consacrer au basketball.',
      "Drafté 9ème en 1998, il a été immédiatement échangé. Les scouts n'étaient pas sûrs que son jeu se traduise en NBA.",
      "Il a révolutionné le poste d'ailier fort avec son tir extérieur, ouvrant la voie aux grands shooteurs modernes.",
      'MVP en 2007, il a mené son équipe au meilleur bilan de la ligue.',
      'En 2011, il a finalement remporté un titre, battant une super équipe en Finales dans une performance légendaire.',
      'Son tir signature - un fadeaway sur une jambe - était pratiquement impossible à contrer.',
      'Il a passé ses 21 saisons avec la même franchise, devenant synonyme de cette équipe.',
      "Il est largement considéré comme le meilleur joueur européen de l'histoire de la NBA.",
    ],
  },
  {
    name: 'Kevin Garnett',
    type: 'legend',
    difficulty: 2,
    hints: [
      'Né en 1976 en Caroline du Sud. Il est entré dans la draft directement depuis le lycée en 1995.',
      "Il était le premier joueur depuis 20 ans à sauter l'université pour la NBA, ouvrant la voie à d'autres.",
      "MVP en 2004, il était le cœur et l'âme de sa franchise pendant plus d'une décennie.",
      "Malgré sa dominance individuelle, il n'a pas pu gagner de titre avec son équipe d'origine.",
      'Transféré à Boston en 2007, il a finalement remporté un titre en 2008 dans un trio légendaire.',
      "Son intensité était légendaire - il criait, parlait trash, et jouait chaque possession comme si c'était la dernière.",
      "Défenseur de l'Année en 2008, il est considéré comme l'un des plus grands défenseurs de l'histoire.",
      "Sa phrase 'Anything is possible!' après son titre est devenue iconique.",
    ],
  },
  {
    name: 'Steve Nash',
    type: 'legend',
    difficulty: 2,
    hints: [
      'Né en 1974 en Afrique du Sud, il a grandi au Canada. Le football (soccer) était son premier sport.',
      'Drafté 15ème en 1996, il était considéré comme trop petit et pas assez athlétique.',
      'Il a remporté deux MVP consécutifs en 2005 et 2006, surprenant beaucoup de gens.',
      "Son style de jeu rapide et son attaque '7 secondes ou moins' ont révolutionné le basketball moderne.",
      "Malgré ses MVP, il n'a jamais atteint les Finales NBA en tant que joueur - une grande déception.",
      "Il était un passeur et shooteur exceptionnel, malgré une vision déficiente d'un œil.",
      'Il a joué ses dernières saisons avec des blessures graves, ne pouvant montrer son vrai niveau.',
      'Après sa carrière de joueur, il est devenu coach, mais avec des résultats mitigés.',
    ],
  },
  {
    name: 'Jason Kidd',
    type: 'legend',
    difficulty: 3,
    hints: [
      "Né en 1973 à San Francisco. Il était l'un des joueurs de lycée les plus recrutés de son époque.",
      'Drafté 2ème en 1994, il a immédiatement montré ses qualités de meneur et de leader.',
      'Il a mené trois franchises différentes aux Finales NBA, gagnant finalement un titre en 2011.',
      'Son QI basket et sa vision du jeu étaient légendaires - triple-double machine avant que ce soit commun.',
      "Co-Rookie de l'Année, il a transformé chaque équipe où il est passé.",
      'Sa défense sur les meneurs était parmi les meilleures de son époque.',
      "Après sa carrière de joueur, il est devenu coach, remportant le titre de Coach de l'Année.",
      "Il a joué un rôle clé dans le titre de 2011 aux côtés d'un ailier fort européen légendaire.",
    ],
  },
  {
    name: 'Ray Allen',
    type: 'legend',
    difficulty: 2,
    hints: [
      'Né en 1975 en Californie. Il a grandi dans des bases militaires à travers le monde.',
      "À l'université du Connecticut, il est devenu une star nationale et a joué dans un film de basketball.",
      'Drafté 5ème en 1996, il était connu pour sa forme de tir parfaite et son éthique de travail.',
      'Il a remporté son premier titre avec Boston en 2008 dans un trio légendaire.',
      'Sa décision de rejoindre Miami en 2012 a été vue comme une trahison par les fans de Boston.',
      "Il a inscrit l'un des tirs les plus importants de l'histoire des Finales, sauvant son équipe de l'élimination.",
      "Il détenait le record de trois points en carrière jusqu'à ce qu'il soit dépassé en 2021.",
      'Sa routine pré-match et son attention aux détails étaient légendaires.',
    ],
  },
  {
    name: 'Isiah Thomas',
    type: 'legend',
    difficulty: 3,
    hints: [
      'Né en 1961 à Chicago, le plus jeune de neuf enfants dans un quartier difficile.',
      "À Indiana, il a mené son équipe au titre NCAA en 1981 avant d'entrer dans la draft.",
      "Drafté 2ème en 1981, il est devenu le leader des 'Bad Boys' de Detroit.",
      "Ces équipes étaient connues pour leur défense physique et intimidante, les 'Jordan Rules'.",
      'Il a remporté deux titres consécutifs en 1989 et 1990, étant nommé MVP des Finales.',
      'Malgré sa petite taille, il jouait avec une férocité et une ténacité inégalées.',
      "Il a été controversiellement exclu de la 'Dream Team' de 1992 à cause de rivalités personnelles.",
      'Après sa carrière de joueur, il a eu des résultats mitigés comme coach et dirigeant.',
    ],
  },
  {
    name: 'John Stockton',
    type: 'legend',
    difficulty: 3,
    hints: [
      "Né en 1962 à Spokane, Washington. Il a joué à l'université de Gonzaga, pas une puissance du basketball à l'époque.",
      "Drafté 16ème en 1984, il n'était pas considéré comme un futur Hall of Famer.",
      "Il détient les records de passes décisives et d'interceptions en carrière - des records qui semblent imbattables.",
      "Il a formé l'un des duos les plus mortels de l'histoire avec un ailier fort dominant.",
      'Il a atteint les Finales NBA deux années consécutives mais a perdu les deux fois contre une dynastie.',
      'Son style de jeu était fondamental, efficace et sans fioritures.',
      'Il a joué 19 saisons avec la même franchise, ne manquant presque jamais de matchs.',
      'Son short court et son apparence ordinaire cachaient un compétiteur féroce.',
    ],
  },
  {
    name: 'Karl Malone',
    type: 'legend',
    difficulty: 2,
    hints: [
      "Né en 1963 en Louisiane. À l'université de Louisiana Tech, il était surnommé pour sa puissance physique.",
      "Drafté 13ème en 1985, il s'est développé en l'un des ailiers forts les plus dominants de l'histoire.",
      'Il a remporté deux MVP (1997, 1999) et a été sélectionné 14 fois au All-Star Game.',
      'Son duo avec un meneur record a terrorisé la ligue pendant presque deux décennies.',
      "Il a atteint les Finales trois fois mais n'a jamais remporté de titre, perdant souvent contre la même équipe.",
      "Le pick-and-roll avec son meneur est devenu l'action la plus redoutée de son époque.",
      "Il est le deuxième meilleur marqueur de l'histoire de la NBA, derrière seulement un joueur.",
      "Sa dernière saison, il a rejoint une équipe rivale à la recherche d'un titre, sans succès.",
    ],
  },
];

async function main(): Promise<void> {
  console.log('🌱 Seeding database with', characters.length, 'characters...\n');

  for (const char of characters) {
    await prisma.character.upsert({
      where: { name: char.name },
      update: {
        type: char.type,
        difficulty: char.difficulty,
        hints: char.hints,
      },
      create: {
        name: char.name,
        type: char.type,
        difficulty: char.difficulty,
        hints: char.hints,
      },
    });
    console.log(`  ✓ ${char.name} (${char.type})`);
  }

  console.log('\n✅ Seeded', characters.length, 'characters');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
